### ISSUE TITLE
Separate the night vision goggles from the nanosuit and changes to the night vision goggles

### ISSUE THREAD

**Issue by Carbon-Ghost** [TinyModularThings/IC2Classic#105]
Self explanatory, I don't want it using a nanosuit helmet in the crafting recipe as it makes no sense because in the end it has less power and doesn't even give you protection. 
I don't want the inverse either because I want the Nanosuit to be standalone..

Instead keep the nightvision goggles as a special utility E-armor ( like jetpack and lappack ) more useful for mining, utility ( exploring for exemple ) and PVP base infiltration :3

As for the crafting recipe, change it a bit, this should be better imo :  
advanced_heat_exchanger:carbon_plate:advanced_heat_exchanger
Luminator:NightVision_Potion_Extended:Luminator
carbon_plate:Reinforced_Glass:carbon_plate

" The luminators coupled with the night vision potion allows advanced electrical night vision, the carbon plate allows the complex small fragile parts to be protected in the main helmet frame, the reinforced glass is welded to the glass of the night vision bottle core, allowing to have clear vision while still having the fragile parts remaining protected, which when illuminated by the luminators in the night vision fluid core behind the head of the user, it makes the whole glass structure that is around the head glow and transmits the low light of the surrounding environment to a clear day-like view to the user eyes. The fluid in the night vision core is cooled by the advanced heat exchangers and the main helmet frame as it's made out of carbon as it's a natural heat conductor, this allows using less light and therefore less energy for the same level of effect of night vision. " -HAYO 2015
Small description of why using this recipe :D 

Also, FFS, remove the blindness effect in the day light, it's annoying, have no purpose in life ( EVERYONE HATES YOU BLINDNESS ), and makes people not wanting to use it :c 

As it's an utility armor like jetpack, it shouldn't give protection imo.

**Comment by Speiger** [comment]
Sry @Carbon-Ghost nope... I can exchange the helmet requirement to another one we will see that but the logic behin the helmet stays. At least for day and night seeing. 
Adding a helper for mining is kind of funny idea maybe i make a mining helmet or something where you can see which ores are in your area (those you can see) So that you do not miss something ^^"

**Comment by Carbon-Ghost** [comment]
So you won't change functionality but what about recipe ? What recipe are you thinking about ?

**Comment by Speiger** [comment]
No Potions -.-" It is a technical recipe which makes already sence without a potion there is no potion required at all...
After all i will change maybe the helmet or something we will see, but the carbone helmet is in this case the energy storage and the helmet base for the Nightvision goggles thats why it is picked... Not because to make it expensive. Try to see the little realistic in the recipe. Why did you think that i added glass to the Steam reactor recipe because it should show that this thing has a Tank in it (because bc made glass = fluidStorage) you know

**Comment by Carbon-Ghost** [comment]
I know, but then remove the nanosuit helmet in the recipe, it make no sense ! Glowstone dust or an electronic circuit would have made more sense :P

**Comment by Speiger** [comment]
Think what happens if you wear a helmet that lights up your vision constantly and you can not turn it of?
You get blind over the day and have to take off the helmet all day and at night you put it in again... So no... Recipe is perfect i make maybe a electric helmet or something which can be used as recipe container

**Comment by Carbon-Ghost** [comment]
Yes pls, because it still doesn't make sense due to the fact that the NVG doesn't provide protection and have way WAY less EU storage :p 

And I know it's logical but minecraft night vision effect only makes dark things "glow" so theoretically due to the helm giving you the same effect, you shouldn't get blinded :/ But I understand what you mean ^^

**Comment by Speiger** [comment]
Effect stays, basehelmet is an option^^

**Comment by Carbon-Ghost** [comment]
^^ Kk, also, should we test RotaryC compat ?

**Comment by Speiger** [comment]
Rotary craft compat should work good. I saw raikas code and also we had a little talk.

**Comment by Carbon-Ghost** [comment]
Hehe nice, gonna open a discussion ticket on RoC thread, are you ok with that ? It's a to test thread ^^

**Comment by Speiger** [comment]
Its fine, but do not expect me with it.

**Comment by Carbon-Ghost** [comment]
kk
