### ISSUE TITLE
Many machines don't work.

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#1114]
Now, jei can only find the recipes of several machines, and none of the other machines will work (no items can be put in).![Image_1709475628178.jpg](https://github.com/TinyModularThings/IC2Classic/assets/126538334/3c6d9ef6-4269-4b2f-8b67-a755ab93cdf8)

**Comment by BeryL12138** [comment]
2.0.9.1

**Comment by Speiger** [comment]
@BeryL12138 could you please provide a video of what you are trying to do. Because the description isn't really helpful

**Comment by BeryL12138** [comment]
> @BeryL12138 could you please provide a video of what you are trying to do. Because the description isn't really helpful

Oh,I fixed this problem after I restarted the game many times.

**Comment by CrossVas** [comment]
Something to add to this issue.
After updating to `2.0.9` and even `2.0.9.1` some recipes stopped working (as expected).
I went into my dev instance and updated my deps and switched to in-code recipe instead of manually added `.json` files.

Here are the recipes (some of them): 
```java
        // macerator
        recipes.macerator.registerListener(a -> a.addSimpleRecipe(new ResourceLocation(ID, "nikolite_maceration"), new ItemStack(CrossRPObjects.NIKOLITE_DUST.get(), 12), CustomTags.NIKOLITE_ORE));

        // extractor
        recipes.extractor.registerListener(a -> a.addSimpleRecipe(new ResourceLocation(ID, "ruby_extraction"), new ItemStack(CrossRPObjects.RUBY.get(), 3), CustomTags.RUBY_ORE));

        // mass fabricator
        CompoundTag ampTag = new CompoundTag();
        ampTag.putInt("Amplifier", 5000);
        recipes.massFabricator.registerListener(a -> a.addSimpleRecipe(new ResourceLocation(ID, "massfab_nikolite"), ic2.core.platform.registries.IC2Items.UUMATTER.getDefaultInstance(), ampTag, CrossRPObjects.NIKOLITE_DUST.get()));
```
The code above seems to work well, as it shows me the recipe I want, but when trying to insert items, it can't seem to be possible.
I went even further, executed the `/ic2c_export` command, I got my recipe `json` files, copied them manually into `data` folder and they worked. No matter what I do in code, I can't get item inserted.
Here is a video:
https://youtu.be/_1FVdfNduhY

And here is the `.json` file for `nikolite_maceration` recipe: 

```json
{
  "input": {
    "tag": "forge:ores/nikolite",
    "size": 1,
    "type": "ic2:tag"
  },
  "output": {
    "xp": 0.0,
    "outputs": [
      {
        "item": "cross_rp:nikolite_dust",
        "size": 12,
        "type": "ic2:nbt"
      }
    ],
    "type": "ic2:simple"
  }
}
```
