### ISSUE TITLE
[1.19.2] Random Server Crash #2

### ISSUE THREAD

**Issue by ObscuriaLithium** [TinyModularThings/IC2Classic#1119]
The public server randomly crashes during the game (Probably for another reason)
IC2 Classic 2.0.9.1, Forge 1.19.2-43.3.8

[crash-2024-03-12_11.28.58-server.txt](https://github.com/TinyModularThings/IC2Classic/files/14576795/crash-2024-03-12_11.28.58-server.txt)

**Comment by Speiger** [comment]
@ObscuriaLithium this one crashes because the grid splitting of monitors takes to long.
Either you have build a monitor that is like millions of blocks big or you have another block deadlocking the main thread from fetching a chunk.

Anyhow since we actively use this server with the latest forge version i can assure you that isn't an problem.

Please reproduce this with vanilla + forge + ic2c alone or figure out which mod is at fault here, because at the moment ic2c isn't at fault.
