### ISSUE TITLE
[Bug] Recycler not working

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#112]
Hi! I returned. and found a small bug in the recycler. It can not load items using any pipes for processing. And if you insert a transformer upgrade it ceases to process things and not take power. Compact recycler works fine. If something is not clear, I can make screenshots or record video. Forge Version 1448 version IC2Classic 1.1.0.19. 

P.S. I apologize for the long absence and assistance. There were things at work.

**Comment by Speiger** [comment]
@Dr0n1k no problem it is ok when you need your time.
It would be good if you can make screenshorts that would help..

**Comment by grydian** [comment]
I just came online to figure out why my recyclers aren't working.  I put two transformer upgrades in them and they wont even accept power from my HV solars.  I tried EnderIO item conduits and ExtrU transfer nodes and neither one could put cobble into the recyclers.  I also can provide screen shots if you like.

**Comment by Speiger** [comment]
@Dr0n1k @grydian. Ok to explain what that was. I fixed it by the way:
When you putted items into the recycler it simply was only consuming items when he created scrap for it (so Success in the luckgame xD). The machine worked how it should with that part.
And the transformer upgrade bug was only visual. It did not accept power because it was already full. So you have a OP recycler with a visual glitch in the current version xD
But that is now fixed.
