### ISSUE TITLE
Can't locate a rocket miner. Looks like chunk loader doesn't work at rocket miner.

### ISSUE THREAD

**Issue by Caesar228** [TinyModularThings/IC2Classic#1133]
Miner flyes into unloaded chunks and doesn't come back

**Comment by Geekerandy** [comment]
How do you know it’s not coming back?
Have you found it and it’s not functioning?
If so, why isn’t it functioning?
If you haven’t found it, have you not used a Miner Remote to find it?
And I presume this is for 1.19.2?

**Comment by Caesar228** [comment]
> How do you know it’s not coming back? Have you found it and it’s not functioning? If so, why isn’t it functioning? If you haven’t found it, have you not used a Miner Remote to find it? And I presume this is for 1.19.2? And are you using the latest IC2C version? State the version number.

It doesn't load chunks when fly away. Yes it was the latest version. But at 2.0.7.1 everything works okay. I turn my server back to  2.0.7.1 until it will be fixed.
 Check it at last version: send miner far away and try to check it with miner remote

**Comment by Speiger** [comment]
@Caesar228 the older version of the rocket miner was a lot messier and buggier then the 2.0.7.1 version.
Yes there was 1 major bug in it, but compared to the 30ish bugs found in the original rocket miner logic, where it could get stuck or simply not work as expected, it is a lot better.

Also we found this bug during our solar panel race an fixed it. Which i simply couldn't upload because I wanted to play and second other projects had priority.

Anyways your comment is 10 hours to late. The patch came out when i closed this issue.
You can downgrade if you want but the patch has been out fixing it for good (and we used roughly 18 rocket miners over a week in parallel)
