### ISSUE TITLE
Visual error: Pipes still render while foamed, and have incorrect lighting.

### ISSUE THREAD

**Issue by AstoriaFloyd** [TinyModularThings/IC2Classic#1139]
Partial duplicate of #1138, with more detail.

I had incorrectly stated that foamed blocks did not render properly due to still being transparent. I have since discovered this is not the case. Rather, after being foamed, wires and pipes cease to render their original forms and become identical to construction foam blocks. Tubes do NOT do this, which I believe is unintentional. Tubes continue to render their original model underneath the construction foam, which would explain the incorrect lighting. It could also help performance if items inside tubes did not render when they are foamed.
Here is the setup I used to test this
![2024-04-05_16 48 51](https://github.com/TinyModularThings/IC2Classic/assets/39976417/f08e67d4-bc06-449b-9021-80577fb8d92b)
![2024-04-05_16 48 53](https://github.com/TinyModularThings/IC2Classic/assets/39976417/5420820c-6ae3-4994-acf3-b5efbbd8ff8f)

![2024-04-05_16 49 27](https://github.com/TinyModularThings/IC2Classic/assets/39976417/faca1403-a2d6-49c9-8038-2ae3831d9296)
![2024-04-05_16 49 33](https://github.com/TinyModularThings/IC2Classic/assets/39976417/5bbab263-20d1-4211-b979-855a30a574b3)
![2024-04-05_16 49 42](https://github.com/TinyModularThings/IC2Classic/assets/39976417/2ab6461a-58f4-4de2-acf8-31fb8a2f39e7)
![2024-04-05_16 49 56](https://github.com/TinyModularThings/IC2Classic/assets/39976417/f5b4a832-fdb6-4b68-a2c7-e93a1f903ce4)
![2024-04-05_16 53 39](https://github.com/TinyModularThings/IC2Classic/assets/39976417/4ad37291-a648-480f-900c-3a1fd69642b5)
![2024-04-05_16 53 49](https://github.com/TinyModularThings/IC2Classic/assets/39976417/8c213082-e221-43e6-ba16-0b300c54dbb0)

**Comment by Speiger** [comment]
@AstoriaFloyd yeah there is a slight difference in code defining which rendertype it is in, the models on the other hand are equal, quite literally.

I will have to look into it deeper and see if that breaks functionality or not or if it solves the problem or not.

About tubes not rendering their stuff when foamed.
The tube itself won't hurt performance since its just another block worth of quads inside of the simple chunk renderer.
Which is the most efficient renderer inside mc itself.
And items only cause render lag if they are inside, and that can be turned of with the tube tool.

But I am at the moment at a coding break due to IRL reasons that are more important then modding.
So don't expect this being addressed anytime soon.
