### ISSUE TITLE
[1.19.2] forge server crash

### ISSUE THREAD

**Issue by wulfwuud** [TinyModularThings/IC2Classic#1147]
[crash-2024-04-15_10.03.32-server.txt](https://github.com/TinyModularThings/IC2Classic/files/14975372/crash-2024-04-15_10.03.32-server.txt)

to reproduce:
Place a lot of hv panels and wires i guess

additional info:
server crashes every time i boot it (after around 1 minute as in crash log)
before crashes started average tps was around 9 or so
in earlier crash logs i found this:
block_entities: 44427 [ic2:crop_sticks:19338,ic2:glassfiber_cable:8699,ic2:super_cable:6291,ic2:solar_panel_hv:5512,ic2:machine_structure:2772]

**Comment by Speiger** [comment]
The enet implementation complexity goes up by sources * sinks * packets on a grid.
A grid is a set of cables.

It is in general a good idea to merge all sources into as little sinks as possible (a buffer) and then use said buffer to feed all machines that way the complexity of the power transfer gets reduced massively.

I am at the moment theorizing a faster implementation but atm your issue is that your energy grid is simply build really expensively in computation.

That's the issue.

This is not a bug. You simply lag out the server so that it emergency shuts down to prevent a lockup.

That time by default is 60 seconds per tick. You can easily increase that in the server properties.

Anyways this is a user problem not a problem with the mod itself.

Tell your users not to combine hundreds of generators directly with hundreds of machines.
