### ISSUE TITLE
[1.12.2] Error in log with Thaumcraft/ThaumicJEI?

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#1151]
https://mclo.gs/83IX6kD

Appears to not like some IC2 Classic advanced recipes?

**Comment by Speiger** [comment]
Hmmm this looks weird.
I will investigate it once I have time.

But this looks like a thaumcraft bug but can't confirm it 100%

The inventory inserted into the function seems fishy.

**Comment by xJon** [comment]
Indeed, it may be a minor Thaumcraft issue - figured to report just in case :)

**Comment by Speiger** [comment]
@xJon this is a thaumcraft bug but i am introducing a "small fix" that should address the issue.
But thats all i can do in that regard.

The problem is thaumcraft isn't checking the recipe before getting the remaining output, and ic2c expects that to happen.
If the check wasn't performed it will now perform the check just in case.
