### ISSUE TITLE
How to use this api?

### ISSUE THREAD

**Issue by liach** [TinyModularThings/IC2Classic#120]
Ref CovertJaguar/Railcraft#685
Is it better to ship the api from this repo (submodule) or copy the code? I afraid that integrating this might make the api shippping harder...

**Comment by Speiger** [comment]
You can download the API and implement it to your source.
Both ways work fine.

Also @liach what of the API do you want to use. Information would be helpfull.

**Comment by liach** [comment]
Just 
> https://github.com/TinyModularThings/IC2Classic/blob/master/ic2/api/energy/tile/IEnergySourceInfo.java

**Comment by Speiger** [comment]
oh ok. Simply the API is updated. Just updated the API for the newest Classic release.
Also the API at that part you ask for will not change in the near future...

**Comment by modmuss50** [comment]
I had to strip the ic2 API out, and then build a jar with just the classic API in, that then allows me to just add a line into my build.gradle

**Comment by modmuss50** [comment]
You should get a maven, with jar files that just contain the ic2 classic api and none of the normal ic2 classic classes.

**Comment by Speiger** [comment]
Sadly i do not know how to make that @modmuss50.
Well for compiling you do not need a Jar. The sourcecode can be used too.

**Comment by modmuss50** [comment]
I have this repo https://github.com/modmuss50/IC2-Classic-API-STANDALONE it is a clone of the ic2 classic api just without all of the ic2 classes.

Then I use my jenkins to build this, and it uploads to my maven: http://maven.modmuss50.me/

In TechReborn I add https://github.com/TechReborn/TechReborn/blob/master/build.gradle#L36 this to tell gradle where to look for dependences. In that build.gradle file I have https://github.com/TechReborn/TechReborn/blob/master/build.gradle#L119 The reason I am using 'shade' not 'compile' is because I want to include this jar into the final release jar. Shading requires a bit more code in the build.gradle

**Comment by Speiger** [comment]
Ok.
(not sure what to answer or todo)

**Comment by modmuss50** [comment]
When I have more time do you want me to help you set one up or something?

**Comment by Speiger** [comment]
would be great. But my time is sadly over... I have in about 1 hour a meeting and have to leave now...

**Comment by modmuss50** [comment]
I don't have the time at the moment

**Comment by Speiger** [comment]
@modmuss50 well i am back at least. Tell me when you have time.

**Comment by modmuss50** [comment]
8:30pm GMT? Not sure what time zone you are in. Are you in irc?

**Comment by Speiger** [comment]
Hmm i am GMT +1. Irc yes. Speiger is my name.

**Comment by modmuss50** [comment]
@Speiger poke me on irc if you are around, I can't seem to find you.

**Comment by Speiger** [comment]
@modmuss50 sry totally forgot you. I was to tiered and went sleep early sry

**Comment by Speiger** [comment]
closing because no need to be open
