### ISSUE TITLE
[1.12.2] Nuclear Reactor - InventoryHandler is disabled

### ISSUE THREAD

**Issue by LunarLambda** [TinyModularThings/IC2Classic#1216]
Trying to automate refueling a nuclear reactor while being able to address individual slots of the reactor inventory (pipes/hopppers/etc have the issue of simply dumping items into the first available slot)

Per https://github.com/cc-tweaked/CC-Tweaked/issues/1187#issuecomment-1295660074 you seemingly can't push/pull items to/from a nuclear reactor via ComputerCraft. So I looked at inventory upgrades. The wiki says that Nuclear Reactors cannot take slot modifiers, so making it work via Automation Upgrade is also ruled out. However it doesn't say anything about the Machine Access Upgrade. However trying to use it on a reactor simply gives the very cryptic message `Failed to load from InventoryHandler. Handler is disabled`.

What's the 'correct'/ic2c supported way to automatically refuel a nuclear reactor while being able to target specific slots for doing so?

**Comment by Speiger** [comment]
@LunarLambda the automation upgrade simply makes all slots accessible from all sides.
Which the reactor already has by default. This is intentional.

First what is the inventory handler:
The inventory handler is simply a manager of slots, it defines what slots are where and which sides can access what slots.
It isn't the inventory itself but a interface to interact between the inventory and the outside world.

Now to the reactor part:
The reactor is a modular inventory that can change its size.
Due to that, the reactor doesn't get a customization in terms of accessibility. Because we can't really know if a lot does exist or not.
On top of that I remembered that I had issues with the customization option when i developed this implementation.
And it was only fixed like at the end of 1.19.2 itself for non reactor blocks that also had a modular inventory.

But even if i have the tech now too. There is another reason why i don't backport the functionality into reactors.
And that is simply that this is also ment to be a design challenge, and have people to figure out how to automate their reactor.
I even provide tools to achieve that. But per slot configuration as you ask for is simply to far IMO at the moment. (This may or may not change)

I know of people who have made stuff work with computer craft but i am not so deeply into it to make that work, since i know computers should be able to pull items in/out of reactors, otherwise hoppers wouldn't work either.

I hope that helps you with your question :)

**Comment by LunarLambda** [comment]
It does answer my question mostly, thank you
The concrete issue wrt to computercraft is that `pushItems`/`pullItems` succeeds, but returns 0 (no items are moved), which is similar to what another user reported in the comment I linked. But from what I understand from reading that thread, this is either intentional on the part of IC2 Classic, or at least not something you want to explicitly support at this time.

I might ask the authors of the CC integration also, it seems like the integration simply pretends the reactor is the max size, with inaccessible slots simply being shown as empty in the API.

Anyway, I appreciate the thorough reply ^^

**Comment by PrincessOfEvil** [comment]
You can always make the reactor easier to automate by dumping "dummy" items
into empty slots. Plating, or component vents.Message ID:
***@***.***>

>
