### ISSUE TITLE
Rocket miner idle state

### ISSUE THREAD

**Issue by Aleksei-Tavadyan** [TinyModularThings/IC2Classic#1221]
Sometimes rocket miner enters idle state without any reason. It has energy, storage space left, pipes and anything else it need to work. 
I've noticed it happened when it land on water or bedrock.

**Comment by Geekerandy** [comment]
Need more information in order to understand what's going on. 
Reproduction steps to help reproduce this bug (if it is one)
Video if applicable
My guess based on what little information you've given, is that the rocket miner is stuck trying to mine in an area it has no access to be able to mine. Such as chunks claimed through FTB Chunks.
You can try to restart the rocket miner by popping the drill out and back in.

**Comment by Speiger** [comment]
@Aleksei-Tavadyan please provide a clip so we can actually see what is happening.
That should include the "probe/Jade" info being on display and a view of the gui too.

**Comment by Aleksei-Tavadyan** [comment]
I've been playing for 2 weeks and this behavior didn't occur, so I guess the issue can now be closed. 
My only theory is that bug was caused by the fact that I placed (initiated) the miner on the same block several times in a row, after which it went into already dug holes and got stuck there. As soon as I placed the miner on another block, it always worked properly.
Thx for ur time guys.
