### ISSUE TITLE
[1.7.10] Suggestion: Adding some IC2 add-ons or making them separate mods

### ISSUE THREAD

**Issue by vizthex123** [TinyModularThings/IC2Classic#1222]
I personally always kinda hated IC2 Experimental, but none of the add-ons I use work with Classic- so I was wondering if it'd be possible for someone to fork the existing ones (or something) so that they work with IC2 Classic.

List:
- Advanced Solar Panels. I always liked it more than CompactSolars, and there could even be a config option to disable the CompactSolars (if there isn't one already).
- Electro-Magic Tools. I know the GTNH team forked this to update it for their pack, and if possible it'd be great to have that version work with IC2 Classic (and getting its own CurseForge page).
- GraviSuite. Would also be nice if the localization errors got fixed. *Both this and ASP having the [patcher](https://www.curseforge.com/minecraft/mc-mods/asp-gs-patcher) built-in would be lovely too.*

Figured I'd make a quick suggestion after remembering this mod.

**Comment by Speiger** [comment]
o/ @vizthex123 glad you enjoy the mod.

About your question. What you ask is technically possible. But I won't be doing that.
Since all ic2c versions are only limited to bugfixes alone, on top of that I don't have the time to deal with that.

But if you do find someone who can do it for you then you should be fine :)

Anyways sorry if that answer isn't within your expectations.
Have a nice time :3

**Comment by vizthex123** [comment]
damn, i figured that'd be the answer. Ah well.
