### ISSUE TITLE
About creating an addon or an add-on to ic2c

### ISSUE THREAD

**Issue by proxima812** [TinyModularThings/IC2Classic#1230]
How can I write (create a new item for the addon, or in ic2 1.19.2 itself, let's say a "quantum solar panel" to make a craft and its parameters, and so on? Please tell me. How can I do this via the ic2 API?

**Comment by Speiger** [comment]
@proxima812
- 1: Install your dev enviorment
- 2: Include these entries in your gradle.build file. Make sure not to blindly copy paste it, but merge it together properly.
```java
repositories {
    maven {
        url "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
}
dependencies {
    implementation fg.deobf("curse.maven:ic2_classic-242942:5612597") 
}
```
- 3: Make sure this code is present within your runs area in gradle.build [Reference](https://github.com/TinyModularThings/IC2Classic/issues/610#issuecomment-1420868810)
```
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
```
- 4: Refresh your gradle. ic2c should now be included.
- 5: Make sure you include a decompiling plugin that way you can also look at the source.
- 6: Look how ic2c implemented the features you wanted. (You are to vague that i can't give better instructions)
- 7: IMPORTANT: Make sure not to blindly copy paste ic2c code otherwise i will have to take your project down. If there is somehting where you have 0 choice (i have to agree with that by the way) then its fine to copy but if not then leave it.
- 8: There is a discord with addon devs present.

**Comment by proxima812** [comment]
> @proxima812
> 
> * 1: Install your dev enviorment
> * 2: Include these entries in your gradle.build file. Make sure not to blindly copy paste it, but merge it together properly.
> 
> ```java
> repositories {
>     maven {
>         url "https://www.cursemaven.com"
>             content {
>                 includeGroup "curse.maven"
>             }
>         }
> }
> dependencies {
>     implementation fg.deobf("curse.maven:ic2_classic-242942:5612597") 
> }
> ```
> 
> * 3: Make sure this code is present within your runs area in gradle.build [Reference](https://github.com/TinyModularThings/IC2Classic/issues/610#issuecomment-1420868810)
> 
> ```
>             property 'mixin.env.remapRefMap', 'true'
>             property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
> ```
> 
> * 4: Refresh your gradle. ic2c should now be included.
> * 5: Make sure you include a decompiling plugin that way you can also look at the source.
> * 6: Look how ic2c implemented the features you wanted. (You are to vague that i can't give better instructions)
> * 7: IMPORTANT: Make sure not to blindly copy paste ic2c code otherwise i will have to take your project down. If there is somehting where you have 0 choice (i have to agree with that by the way) then its fine to copy but if not then leave it.
> * 8: There is a discord with addon devs present.

OK. I'll try to make an addon separately, like advanced solars panels.

**Comment by CrossVas** [comment]
> OK. I'll try to make an addon separately, like advanced solars panels.

https://www.curseforge.com/minecraft/mc-mods/advanced-solars-classic

**Comment by proxima812** [comment]
> > OK. I'll try to make an addon separately, like advanced solars panels.
> 
> https://www.curseforge.com/minecraft/mc-mods/advanced-solars-classic

Yes, I'm just studying its source code. I'll just add what I need there.

**Comment by proxima812** [comment]
> > OK. I'll try to make an addon separately, like advanced solars panels.
> 
> https://www.curseforge.com/minecraft/mc-mods/advanced-solars-classic

### I created two of them: quantum and photonic

![Снимок экрана 2024-12-07 в 15 36 33](https://github.com/user-attachments/assets/efae376f-9802-4733-a1cc-8df0a30a729e)
![Снимок экрана 2024-12-07 в 15 36 28](https://github.com/user-attachments/assets/8faa6095-1cd6-45ee-a48c-7b2d8c7d6d8b)
![Снимок экрана 2024-12-07 в 15 36 21](https://github.com/user-attachments/assets/668c0d56-6232-4276-aee8-b48b46b013b3)
![Снимок экрана 2024-12-07 в 15 36 37](https://github.com/user-attachments/assets/5f556cb2-c1fe-4581-a418-51a7da48cd96)
