### ISSUE TITLE
Support For TerraFirmaCraft

### ISSUE THREAD

**Issue by dexman545** [TinyModularThings/IC2Classic#152]
Hello, I make a modpack that uses TFC (I would also like permission to use IC2 Classic in it), and I was wondering if it would be at all possible for support for TFC to be added to IC2 Classic. 

Out of the Box issues:
TFC has wrought iron, with no way of obtaining vanilla iron.
Rubber trees don't appear to spawn
TFC allows for the cutting of the whole tree with one block, but requires the item to be ore dicted
    as itemAxe for this to be possible (The chainsaw would need to be registered with this to chop a 
    whole tree in one go)
Would it be possible to show in NEI that pitcheblende can be macerated for uranium?
TFC has its own armour (vanilla armour is not avaiable)
TFC has its own damage system. Weapons would need to have their damage buffed
TFC has no vanilla diamonds, but it does have its own versions of them (not really an issue, vanilla 
  diamonds can be made in IC2's system)
TFC has its own coal
IC2 crops do not take nutrients from soil
IC2 crops system doesn't work with TFC crops, or soil
IC2 armour is practically worthless in TFC damage system
IC2 drinks do not fill thirst from TFC (not that big of an issue)
IC2 has custom water, fluid cells do not work with it
Haven't tested production of scrap, nor the mining machine native to IC2 yet.

Thank you,
dex

**Comment by Speiger** [comment]
@dexman545 o.O Holy crap.... Sry for that but i had to take a drink first before i answer that (just water)...
Thanks for that request... I am not sure if i am able to do that... (Because it would require maybe a whole rewirte). But i can say i like this idea. I will at least look into it and tell you if it is possible^^"

**Comment by dexman545** [comment]
Cool, thank you very much :). I can handle crafting table recipes with Minetweaker (Haven't tested if Modtweaker IC2-Exp support will work with IC2 classic yet, so machine recipes IDK about). For my purposes, rubber trees not spawning isn't a huge issue, I have Electrical Age in my pack, so I have other ways of getting resin.

**Comment by Speiger** [comment]
ok. First ModTweaker (is a minetweaker plugin i think) supports the IC2 API which supports both classic and Exp so no worries about that^^. And i think when i support that mod then with everything. (Including recipe support)

**Comment by dexman545** [comment]
Ok, then, I should be able to handle the recipes myself. I might be able to handle the water by making IC2 classic load after TFC Water Compatibility (not sure on this). For damage values (I don't know Java, so I'm just making some stabs), maybe having a soft dependency for TFC that changes the damage/durability of the weapons/armor might work...

**Comment by Speiger** [comment]
No worry about that... I can make direct Mod Support without any dependency^^" So no worry.
We will see how the support is gonna happen... It could be also possible that it will be a seperate mod for classic only... ^^

**Comment by dexman545** [comment]
Ooh, nice. Thank you for the help!

BTW, may I use IC2 Classic (and the TFC support addon for IC2 Classic, if it is a separate mod) in my modpack, Technofirma?
Pack link: http://forum.feed-the-beast.com/threads/1-7-10-technofirma-terrafirmacraft-modpack.49502/

**Comment by Speiger** [comment]
^^

**Comment by dexman545** [comment]
Is it still possible to have IC2 reactors output steam instead of power directly? I looked in the config, and that doesn't seem to be the case anymore.

**Comment by Speiger** [comment]
@dexman545 its now a seperate reactor which you build of the reactor and other components. 
You require Steam vents for them to produce steam. 
Note: 
-The reactor does not autoeject steam.
-Steam vents produce only steam if the reactor can accept steam (in his internal tank)
-Steam vents cool only the reactor if the steam gets pusht into the reactor.
-Normal Heat vents simply cool the steam reactor but causes only energywaste...

**Comment by hron84** [comment]
I think coal issue can be solved as MineTweaker has not only recipe support, but also machine support too. Adding a recipe that macerates TFC coal to coal dust does not sound too hard. The biggest issue I think is making the damage systems compatible.

For soil problem: temporarily, adding a recipe that makes vanilla dirt from various TFC dirt should solve the IC2 crops soil problem. Supporting TFC crops is unneccessary I think, because their own behavior (uprooting when the conditions aren't good enough).

**Comment by Speiger** [comment]
@dexman545 i asked for a little help at the tfc side. (Not coding just information) and the answer i got was more then i expected. I am not sure if i am going to support it or not (in this version). Simply because it requires not simple changes or some class overrides. Nope it requires a full rewrite of the mod. Which i think is not on my todolist for this mc version. Simply because i am thinking that the version i will release soon will be the last for 1.7.10 (well fixes not included) and i think i would push the update so far out that it would not be worth doing... :/ i am not talking about a week project here.  I think that would take at least a full month...

**Comment by dexman545** [comment]
ahh, well, ok then. Kinda expected it too. Thank you for considering it!

**Comment by Speiger** [comment]
@dexman545 1.8 will be a differend thin. :3
