### ISSUE TITLE
Charge Pads.

### ISSUE THREAD

**Issue by BlesseNtumble** [TinyModularThings/IC2Classic#154]
Good afternoon.
I have a small request.
Can you add Charge pades of Ic2 Exp or addon ChargePads?

**Comment by Speiger** [comment]
Thanks for that feature request^^"
Not sure if i am going to implement it but i like the idea.

**Comment by Carbon-Ghost** [comment]
we should do slabs charge pads imo... if we do it

**Comment by Speiger** [comment]
Well Chargepads will join. How big their EnergyStorage is and transferrate and all that stuff is not deadSet yet but we will see...

**Comment by hron84** [comment]
@Speiger I think you can use same storage as the block has you craft it from. For example, batbox charger should have same store as an original batbox had.

Also, it would be a good idea if the stored EU (remember, wrenching up energy stores keeps EU in the storage) can be transferred to the newly crafted block (situation: at early game, i make a batbox, a bit later I have enough resource to upgrade it to a batbox charger, but I do not want to lost the EU that tne block contains).

**Comment by Speiger** [comment]
@hron84 well the blocklogic is already finished (and they can be used but not crafted). And yeah thats what i went with. I copied the original storages from the original ChargePad mod...

And what you request i simply say no to it... They do lose their complet energy when you break them. Simply because i do not want that the inventory starts to get crappy full... Simply the problem you have in IC2 Exp that you can not stack any EnergyStorage or transformers...
Be happy that the energyExplode feature does not join the game^^"

**Comment by hron84** [comment]
I usually operate IC2 machines without any explode. I always use Mark I reactor designs as I do not need a crazy amount of power. So, I'm a safe player, I can deal with it. Other guys... will be sad if energyExplode will join at some point.

**Comment by Speiger** [comment]
@hron84 the EnergyExplode feature is based around that you cause a explosion when you pick the Chargepad up when it has charge in it... And the Nuke Version of it causes a NuclearExplosion...
