### ISSUE TITLE
Add more contents...

### ISSUE THREAD

**Issue by Pilad** [TinyModularThings/IC2Classic#155]
Please add tiers for watermill and windmill , like as tiers solarpanels.
And add more machines to process ore as the experemental version IC2
Please add more nuclear fuel : thorium, lithium
Add aesu+ high capacity.
Thanks )))

**Comment by Speiger** [comment]
@Pilad 
Well we did plan about it but lag is also a issue with them... (Windmills and Watermills)
About ore processing.. Well i have no really cool or creative idea of process ores better (maybe a suggestion on that?)
Nuclear Reactors had plans to be changed for fuels for quite a while... How much i am going to add only the stars know that^^"
AESU is not needed. With the BatteryStation (and addon mods) you can make a way bigger Energy Buffer... (my AESU version)

**Comment by Pilad** [comment]
Make a copy of the processing of ore with an experimental version IC2.
Or may be multiblocks such us GregTech (TechRebourn mod).

**Comment by Speiger** [comment]
@Pilad oh well...
I do not really like to play the copycat card... Maybe i get a interesting new way....

**Comment by Carbon-Ghost** [comment]
@Pilad 
1 : I may do that ... see below what I mean
2 : No, they are bad :P Imo at least. 
3 : I may also do that... again see below
4 : For AESU, worry not, I'm developping an addon that brings back old GT machines to 1.7.10, because TechReborn team are too busy with IC2 exp, they left classic too buggy, so I asked Greg and he gave me permission to do that, there will minor differences but otherwise you will like the mod :D 
AESU will make a return under another form, it's a bit complicated, once I release it,  I will explain what is planned.

**Comment by Pilad** [comment]
Maybe add the generation of chemical components in the map? Thereafter, water and mixed with each other in the mechanism, then the liquid transfer to next mechanism in the following, and chemically treating the ore.

**Comment by Pilad** [comment]
Add oil to worldgen.Distillation tower for creation benzin, kerosene and etc.Add possible mechanisms of transport and sorting for example as a red power.

**Comment by grydian** [comment]
I wouldn't mind a mid game multiblock structure that gave higher outputs on processing ores.  Expensive with lots of advanced machine parts.  Anyways just a thought.

**Comment by Speiger** [comment]
@Pilad @grydian i know Multiblock Structures look cool and IC2 Classic has only 2 of them (Well the old Kind... Reactors) but you have to keep in mind that Multiblock Structures are simply only: LAGGGGGGGG in any term. Connected Textures/Special Models = Lag, Cacluating if all blocks there = lagg, World Load = Extra Lag. I can understand why people would love to have Multistructures but when i look into letsplays people also say: My world starts to lag. In most cases it has nothing Todo with IC2 Because nobody uses it. (Neither Classic or Exp). So the question is? Do i take the laggy rout or do i ensure that you can play as long as you want (and go crazy with IC2) and have no problems with TPS/FPS or do you want multistructures at the cost of gameplaytime...

**Comment by grydian** [comment]
Fair enough you make many great points in regards to multiblock structures.  How about a single block that is very expensive that does that.

**Comment by Speiger** [comment]
@grydian what do you think is a Nuclear Reactor. (It is not a processing Plant but still its the idea how IC2 Went). ^^"

**Comment by grydian** [comment]
I meant an advanced expensive macerator that more than doubles your ore at high speeds and consume massive amounts of power.

**Comment by Speiger** [comment]
I know. Just wanted to reference that this idea is not unknowen and will be maybe followed. (See the Rotary Macerator Recipe xDD)

**Comment by modmuss50** [comment]
TechReborn works fine with classic, If it doesnt I didnt know about it.

**Comment by Speiger** [comment]
@modmuss50 lets ask @Carbon-Ghost about that since he test all that stuff for you xDD

**Comment by Carbon-Ghost** [comment]
Worked fine except for recipes last time I tried playing it, I don't play much minecraft due to me myself making a mod and school stuff.
