### ISSUE TITLE
Some items from GraviSuite addon don't charge in MFSU

### ISSUE THREAD

**Issue by nikita488** [TinyModularThings/IC2Classic#158]
I try to charge GraviChestPlate or Ultimate Lappack, but i can't put it in MFSU...

**Comment by Speiger** [comment]
Simply because the MFSU is a to low tier... Almost every IC2 addon is based around IC2 Exp which they increased the MFSU tier to 4 instead of 3 (which is the classic tier of a mfsu) to charge them you need to use a BatteryBox which simply ignories tiers and charges them nomatter what...
(It simply simulates the required tier)
