### ISSUE TITLE
Error Wires appearing in console when unloading chunks

### ISSUE THREAD

**Issue by Rubbertjuh** [TinyModularThings/IC2Classic#161]
http://pastebin.com/UPPPTaUm
Hello, I'm having this issue with Industrial Craft 2 Wires when the chunk is being unloaded. I'm running a CB 1.7.10 Thermos ( Fork of kCauldron ) server. This error gets thrown every 2 seconds or so. Pretty annoying. I'm hoping for a fix and will give as much information as possible.
This error started showing up like 1 week after I reset the map. I'm sure that I reset all the data. 
Running a Tekkit Legends modpack.

Seems to be similar to #148

**Comment by Speiger** [comment]
@Rubbertjuh do you run on the latest version? Tekkit legends is not on the latest version... I Poke them right now again to fix that...

**Comment by Rubbertjuh** [comment]
We're running 2 versions behind I think. running version: v1.1.3.5
I tweeted them multiple times to ask if they could update to the most recent version. No luck yet :(
Would it be possible that this error causes some lag as well?

You will poke them right now to fix the error or? 
If there is already a commit for it in the newer version(Which I havent found yet) could you link me to it? I'll find a way to change the code for the version we are using.

Thank you for your reply !

**Comment by Speiger** [comment]
Well its actually only 1 version. (1.1.3.6 is not a public version). 
And yeah i did directly talk to them and they said that they have a update in progress.
About your question, yeah because it keeps loading & unloading chunks. The version 1.1.3.7 fixes this bug and also reduce the server lag imensly. 
Also just a note: This version has not much changed. Just some fixes which are all serversided so you can put it in your instance. It is also backwards (1.1.3.5) compatible.
You can find the download here at the releses page.

**Comment by Rubbertjuh** [comment]
Oh wow! I wasn't aware that it's possible to use 1.1.3.7 on a modpack without them having to change it as well. 
But if you think about it it's pretty logical!
How do I know if cetain fixes are server side only? 
Besides the file name, do I need to change anything else? Maybe the version inside the version.yml?

Thanks a lot for the help! Great support

**Comment by Speiger** [comment]
Well you can not know if they are not serverside only. But i told you that. I think replace the modjar that should be enough to update.
Simple info if you want to update a mod:
-No Blocks/Items Did change?
-Fixes seem to not effect the world?
-Changelog says nothing about: New World Required
Then you are fine.
IC2 Classic you are fine. But next update (the update after 1.1.3.7) will be not backwards compatible (so updated once to the latest it will be hard downgrading (because i add new blocks&Items)
