### ISSUE TITLE
Crash with thermal recycling and IC2

### ISSUE THREAD

**Issue by parcel31u** [TinyModularThings/IC2Classic#165]
http://pastebin.com/Ae3Q9L2N

**Comment by Speiger** [comment]
thanks hopefully that get fixed...

**Comment by Dr0n1k** [comment]
This problem Thermal Recycling. In a class that is responsible for retrieving items from the IC2 given the name of an experimental capsule versions IC2: itemEmptyСell. In this version of the capsule called IC2.item.itemEmptyCell. I for myself rebuild Thermal recycling. I think that this problem is not IC2, and the problem of Thermal recycling.

**Comment by Speiger** [comment]
https://github.com/OreCruncher/ThermalRecycling/issues/98#issuecomment-198959423

**Comment by Speiger** [comment]
@parcel31u well thats a
