### ISSUE TITLE
Suggestion: Reactor planner enhancements

### ISSUE THREAD

**Issue by Renegade2** [TinyModularThings/IC2Classic#175]
when I was using the Ic2 classic reactor planner,i noticed it could use a few improvements.back in Ic2 before the experimental updates,there was a java based Ic2 reactor planner v3. My idea is to make a 'hybrid' planner based off both versions,or even a recode of the original v3 planner to include the additional components added in the ic2 classic.here is a link to the original,as well as i few ideas I have for the planner; 

  (www.talonfiremage.pwp.blueyonder.co.uk/v3/reactorplanner.html)

1) Add a option to toggle the amount of chambers in use,as well as a grid so you can line up the components like in the actual reactor. (http://prntscr.com/b429cq)

2) all the different components (vents,plating,and cells) on one page instead of the left and right arrows.

3) additional information (original planner include component costs,and even the emc values.

4) Separate tabs for regular reactor and steam reactor components.

On a unrelated note I Had a few more ideas;

1) With the rotary macerator you used to be able to add overclockers,and be able to applay a redstone signal to maintain the speed % of the machine at the cost of a constant eu drain.

2) The ability to put the EU reader in the baubles amulet or belt slot and still be able to use it.

**Comment by Speiger** [comment]
@Renegade2 you know i build it based the idea and code of ReactorPlanner V3 in the first place.

1: Easier said then done. Because Containerupdates (changing slots) is not that easy to handle...
Also it requires a lot more differend types of guis... The logic needs to be ajusted too...
2: well the gui already eats a lot of space... And i can not easy expand it. (256x256 scale is a requirement)
3: Yeah i decided against that because i wanted to keep it equal to the actual recipes...
And compiling that down is a lot of calculation...
4: well thats easier then 1-2...

**Comment by Speiger** [comment]
@Renegade2 would be great if you get me some input because i reached the Reactor Planner and would like to get some details done

**Comment by Speiger** [comment]
@Renegade2 look forward to the next 1.7.10 release there you can test the new ReactorPlanner V2
