### ISSUE TITLE
Terraformer

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#18]
It's meant to be able to take 512 EU/t, but yours has a pathetic limit of 32EU/t :P

Also, they seem not to work. Unless they work stupidly slowly.

**Comment by Speiger** [comment]
Ok. That is weird... I checked the source and it is telling 512 EU...

**Comment by Speiger** [comment]
I check that now...

**Comment by Speiger** [comment]
Terraformer/Massfabricator and a lot of other machines was effected by that bug..
I made a quick fix. for both versions 1.6.4 was harder to fix then 1.7.10.... Since i am limited by the api of ic2 exp. I am just adding now the FluidOMat to 1.7.10 (almost done) and then i will make another release...
