### ISSUE TITLE
Mode switch bug

### ISSUE THREAD

**Issue by soulgriever** [TinyModularThings/IC2Classic#195]
when switching between modes of mining laser, jetpack, and wrench when connected to a server it continues to switch mods rather than function.
example. switch to long range mode on mining laser (release mode switch key) keep cycling through modes when attempting to fire laser. I have to select my mode, then use another tool like a drill to make a block change then go back to the laser and hope its in the mode I selected.

works fine in single player
Perhaps a sync issue?

**Comment by Speiger** [comment]
Ok that was a bug/derp on my Side...
I was wonderring why that would happen... 
Reason beeing: 
To prevent massive Packets (every tick) when pressing always the same keys i am allowing only to send a packet when the lastKey state != the  current keyState (so if you keep the same buttons pressed that will not say the server: hey he is pressing these buttons even so he knows that already)
And i forgot or removed that the lastKeyState will be set to the current keyState if something is not equal... So yeah... Derp on my side... 
But here is a temporary thing. change the hud key to any easy key you always use because it is just a dead key for ic2exp support. that will force a trigger of updating the last key state (because it does not update the last key state the last key state is always: Nothing pressed so yeah)
But i fixed it...

**Comment by Speiger** [comment]
Anything else? @soulgriever 
I give you 48hours to find any other bugs. Then i throw a release & for a couple weeks no fix updates...
(also give me some times to remember some bugs i had or compat i wanted to add to it)
