### ISSUE TITLE
Resource Packs

### ISSUE THREAD

**Issue by ThisisCanada98** [TinyModularThings/IC2Classic#200]
Ive just begun using resoucre packs with IC2 Classis, the one I use the most Is faithful 32x modded. WIth all of the packs though there is a common theme with ic2 classic having alot of its textures being off. Such as tin ingot being a battery.

**Comment by Speiger** [comment]
@ThisisCanada98 that could be true. Maybe because since the 1.2 update because i changed the texture sprites because it was 1 ItemSprite for all Items and it was getting full.... And i decided to make it into 4 Sprites with categories... pulling in @DZCreeper who is one of the Authors of faithful 32x
This is not a IC2Classic fault in this case... (You can be lucky that IC2Classic runs with a that outdated  texture pack)

**Comment by yaroslav4167** [comment]
@ThisisCanada98 My port on 1.2.0.4 [here](https://1drv.ms/u/s!Aqpxs79I3ZgdiBu3z6XkWsA7NGsX).
(Ported blocks and items)

**Comment by ThisisCanada98** [comment]
Thank you very much @yaroslav4167
