### ISSUE TITLE
Importing parts of QuantumCatExpansion...

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#213]
Sadly he removed his name so i had to push it out of my mind. (The name)
- [x] Decorative Reinforced Stone
- [x] Decorative Reinforced Glass

**Comment by Reoseah** [comment]
Reinforced Glass Panes?..

**Comment by Speiger** [comment]
@Reoseah any other suggestions?

**Comment by Reoseah** [comment]
@Speiger Just afraid that you could forget panes... I found that is the most usable thing from all of them )

But I had one small idea awaikening me in the middle of the night:
There are painters in ic2 used to color construction foam and any other dyeable blocks. 
And here is idea: make special painter with Uranium instead of dye... 

It dyes everything just like ordinal painters do, but the result is lime-green blocks that emit dim light.
Idea evolved from Uranium Glass that I had at some time in Reinforcement/QCE. If IC2 had machine like Induction Smelter in ThermalExpansion, it would be easy to add recipe for it from glass and uranium. But IC2 had not, so it is hard to make any meaningful crafting for it... And then I remembered painters.

It's somewhat useless, but can be fun... Perhaps, when you live inside a reactor and your torches have all ended xD
If you are using TEBlocks for storing color of cables, then it shouldn't be problem in adding new color. For ordinal blocks it shouldn't be problem at all.
If needed, I can make needed textures (Glass, Wool, Hardened Clay, Construction Foam and, perhaps, Cables).

Last but not least, more game-play value can be added to them by "employment" them in radiation or reactor effects ;3

**Comment by Reoseah** [comment]
It can be simple, nice destructive effect of some overpowered reactor fuel, I think

**Comment by Speiger** [comment]
Interesting idea. But i need to read it in a more calm invioment to understand it fully^^" So wait a bit for my answer

**Comment by Speiger** [comment]
So your idea is making a Uranium Painter which will simply apply a glow effect from blocks & will cause damage if you colide with them If i understand it right. First yes i am using TileEntityBlocks for cables machines etc.... But not like IC2Exp because i dislike the Infinite BlockID system because it has way to many flaws in it to be "Designed good". See IC2GlassFiber cables are no longer seethrough (and yeah thats a bug because of that).
About the idea itself... It sounds funny but i highly doubt that you could use this inside the core... That sounds extremly for me like addon what could do that... ^^" But a glowing version fo Reinforced glass maybe combinig it with glowstone or something?

**Comment by Speiger** [comment]
@Reoseah

**Comment by Reoseah** [comment]
I haven't meant any damage for entities. Uranium Glass IRL is nearly not radioactive as glass absorbs all particles from that small concentration of uranium...
I thought of it as building blocks for more post-apocalyptic buildings.

As for just glowing version of glass... Speaking frankly, I think it is somewhat silly... not the thing I would expect from IC2.

**Comment by Speiger** [comment]
So radiated glass Interesting. But instead of Making it with a painter why not making a radiation absorbing cell which you can use with crafting the type of glass?

**Comment by Reoseah** [comment]
Also: just as I had Cracked Reinforced Stone in Reinforcement, I can make machine block texture with cracks over it. Perhaps, I can make even some basic machines "broken" textures. Those can be used for some "post-apocalyptic" structures in world made from cracked/mossy reinforced stone and some machinery inside; perhaps, also zombie or other spawner inside or rare  IC2 flowers like Aurelia those can be explained by mutation caused by radiation.

**Comment by Speiger** [comment]
So more post appocalyptic machines? I assume that should be a seperate block?

**Comment by Reoseah** [comment]
@Speiger I'm not sure that I understood what you've meant by "radiated" glass...  Uranium glass looks like this when exposed to sun or fluorescent light: https://commons.wikimedia.org/wiki/File:U_glass_above.jpg
And under UV-light it glows with green color. Under light without UV-spectre it is just dirty-yellow (if not colored by other elements).
Some gallery: https://commons.wikimedia.org/wiki/Category:Uranium_glass

**Comment by Speiger** [comment]
o.o

**Comment by Reoseah** [comment]
@Speiger I meant broken machines that do nothing. Or they do something strange: absorb energy losing it, damage entities touching it when powered, damage entities nearby like Tesla coil, or even charge up creepers... Maybe those can drop instead of machine block when you break them with pickaxe or on failing of dismantling.
Obtained they can be crafted into Machine Block in inventory.
Or, possibly, repaired with wrench in crafting table

**Comment by Reoseah** [comment]
Oh, they have no gui as it will be useless

**Comment by Speiger** [comment]
interesting idea. XD

**Comment by Reoseah** [comment]
If IC2 would have a machine or some other way to uncraft items, it can turn the broken machines into resources required to make their normal version. I mean some iron, wires, batteries. Perhaps, slightly less then needed to craft it. If it is macerator with few outputs, then it will output dusts of those resources... 

Maybe such awesome machine can be only craftable using resources from described earlier ruins, just like uncrafting table in TheTwilightForest

**Comment by Speiger** [comment]
*cough* there is a reason why i dropped a big chunk of IC2Exps Recipe API to make these things even possible with already implemented machines *cough*

**Comment by Reoseah** [comment]
... and there can stand RTG generator with one-two energy pellets used at 50-75% (which is many thousands of minecraft days!) powering up those eerie machines of death only awaiting to short-circuit on somebody ...

**Comment by Speiger** [comment]
lol Classic has no RTG Fuel xD And no RTG Generator

**Comment by Reoseah** [comment]
Oh... One-block reactor with some everlasting fuel?

**Comment by Speiger** [comment]
i was thinking about adding that kind of fuel.... a very long lasting fuel....

**Comment by Reoseah** [comment]
Very expensive to player to create, lke RTG in IC2 Exp., like using a lot of prismarine processed through a long line of maceration-extraction-compression-crafting-compression (for example)?

**Comment by Speiger** [comment]
I was thinking making a Uranium Fuel Cell (like a Coal Fuel cell) which you have to fill up in a reactor and then can use it in canner to make a good fueled Fuel Can and then that can be used in a generator.
Since Fuelcans only provide 500Fuel it should be fine.

**Comment by Speiger** [comment]
by the way @Reoseah any idea for SteamLike Achievements or Trackable Stats?

**Comment by Reoseah** [comment]
Oh, no. I think IC2 already had some achievements, like exploding on own nuke?

**Comment by Speiger** [comment]
Well i am actually adding like new achievements. And tracking a lot of stuff... Like if you are more Clean or Dirty Energy Producer or how much EU you have used as player (items), how much items you did produce (automated / manual) and how often you got drunk. How much you did fly with IC2Jetpacks etc xD So if you have ideas xD Tell it xD

**Comment by Reoseah** [comment]
@Speiger I have no ideas about achievements or stats =_= Does somebody needs it?

This is short list of things I suggest:
- Uranium Painter & blocks dyed with it
- Broken Machines that short-circuit or violently explode on touching/breaking/dismantling/just walking near when powered. Those dropped on incorrect breaking of normal machines or spawn naturally in world. Tier of original machine defines how destructive they are.
- Something that work as shapeless recipe in other direction. It can disassemble industrial items back into components and also works for broken machines.
- Some ruins from reinforced stone with some broken machinery inside. May contain basic industrial resources and rare plants/seeds.

I can draw that if needed... I'm experimenting with modding and trying to implements few ideas now, but I think I can find some time for texturing.
