### ISSUE TITLE
About Hammer...

### ISSUE THREAD

**Issue by frank89722** [TinyModularThings/IC2Classic#218]
Hello Sir, I'm playing ic2classic with techreborn and it have a big issue, techreborn miss all metal plate recipes cause ic2classic don't have a hammer.
I know my request it's strange but can you add a hammer in ic2classic? Techreborn stopped all support for 1.7.10 
https://github.com/TechReborn/TechReborn/issues/392

Hope you can do this. Please :(

**Comment by Speiger** [comment]
1.7.10 is still supported yes.
But I won't add a hammer even for a compat.
On top of that I would never suggest you to use TechReborn because its
A buggy mess and the devs seem to be incapable of doing their work properly.
Nothing against modmuss but ic2c compat is the least of your problems in that mod.
(even the artist of their mod doesn't like the state which the mod is in)
