### ISSUE TITLE
Bronze breaks the game with a NullPointer Exception

### ISSUE THREAD

**Issue by esotericdesign** [TinyModularThings/IC2Classic#256]
If a bronze tool is placed in an anvil to be repaired, Minecraft crashes with an Updating Screen Events exception instead of showing repaired item durability along with enchantment cost. 
I just had that NullPointer trying to create one Bronze Hoe from two, though I recall the same error back in the day I was playing with the older mod version. Not sure if it was Bronze Hoe back then, though.
1.7.10, mod version 1.2.1.7
Logs included
[fml-client-latest.log](https://github.com/TinyModularThings/IC2Classic/files/2228550/fml-client-latest.log)

**Comment by Speiger** [comment]
Yeah a loading order causes that issue. I can fix that really simple. But it might take a bit because i usually batch fix stuff and the buffer of "issues" right now is not full enough (and i need to setup a dev envioment for ic2c because i dont have it anymore (to many dependencies))
I leave this open until i fix it.
