### ISSUE TITLE
( Not really an Issue ) but IMPORTANT

### ISSUE THREAD

**Issue by Carbon-Ghost** [TinyModularThings/IC2Classic#27]
Speiger, you have a problem, you have been banned on the forum of IC2 for 3 weeks, we are trying to reduce/remove the ban, but I created this "issue" to keep you informed of what is happening, you have been banned due to AdFly link usage, which is banned on the forum due to Malware/Money income, SpwnX says you should have listenned to him for not having problems with others IC2 devs. He, me and Greg are atm helping you ^.^

**Comment by Speiger** [comment]
Ok i know that i was banned and why it happend to (since i was not able to go into the wiki but was able to ready the first line / topic from aromas mail) where it stayed why i was banned.
Thanks for the info how long i am banned. I was not sure if it was forever and i did forgot that adfly link that caused it.
Well i think its ok that i am now out for 30 days so i can at least work now in the hidden world. But since they did only a account blockage and not like MinecraftForge a IP blockage it is not really a thing for me.
Thanks and say greg that i know that he was not the man of blocking me and i really did not think he would do that. From aroma i did expect it but with a 24hours delay so i can at least prepair myself xD
Anyway thanks @Carbon-Ghost, Spawn X and Greg :)
Anyway i am still in the IC2 Forum each day and look whats going on. But now i have the rule: only looking not touching to follow which is totally ok.

^^ Speiger

**Comment by Carbon-Ghost** [comment]
I told them you forgot to remove adFly on old links, also, I will tell Greg that if you want, I also saw on the Shoutbox that Aroma wanted to ban you for 1 week from what I understood but due to forum being complex with "warning points", he banned you instead for more, SpwnX asked to reduce the time to one week and it was the original time anyway, so, yeah, sorry, did my best     . . '' 

Will you still release updates though or you will take a break ?

**Comment by Speiger** [comment]
@Carbon-Ghost no problem and thanks. ^^"
Well first of all i will work on the mod. I will make the bugfix and then rest a couple days.
We will see how everything comes...
Also just for the note: The Adfly link i was warned is a differend one which i was banned from.
The warned one is which i released IC2 Classic 1.7.10 on the github page here.
The one which i was banned from was the Adfly link to the really old versions of Ic2 classic 1.6.4
So the warnings are from differend things but i really do not care if i am 3 weeks out or if i am 1 week out, ^^"

**Comment by Carbon-Ghost** [comment]
Kk, take care of yourself Speiger ^^

**Comment by Speiger** [comment]
:)

**Comment by Carbon-Ghost** [comment]
^.^

**Comment by Carbon-Ghost** [comment]
You are no longer banned fyi :D .
