### ISSUE TITLE
CF Walls retextured with the Obscurator have a missing texture for a split second when joining

### ISSUE THREAD

**Issue by coderbot16** [TinyModularThings/IC2Classic#271]
Issue stated in title.

This appears to just be an issue from the BlockWallTextured block entities not getting update packets in time. However, this makes these blocks less useful for purposes such as making one-way windows, as their location is revealed whenever you open the world / join the server.

It seems like it is possible to send BlockEntity update packets with the initial chunk packets, like in the case of vanilla tile entities such as banners, which don't suffer from any pop-in issues, even with patterns that require NBT data. Perhaps this can be applied to IC2C machines as well, as it seems that they either delay their update packets or use delayed PluginMessage packets.

While joining:
![2018-09-29_14 26 31_2](https://user-images.githubusercontent.com/22420959/46250754-37c79d00-c3f6-11e8-84f3-9142de1bb348.png)

After loaded in:
![2018-09-29_14 26 32](https://user-images.githubusercontent.com/22420959/46250755-3ac28d80-c3f6-11e8-8014-cf27c7394cda.png)

**Comment by Speiger** [comment]
Yeah, IC2 Blocks request a Data packet when they get loaded and then they get the data. Thats ment for so that less NBTData is send over and only things that are actually needed get over. (Saving mcs memory overhead).
That is sadly the cost of such a feature, but honestly the whole mod is based around this.

Sry but not a bug, just a slowness on the data you receive.

**Comment by coderbot16** [comment]
Ah. I was already aware that the issue is that IC2 doesn't appear to use the standard vanilla BE sync methods. I was just curious if the foam walls could get an exemption because their texture is a lot more critical than the things that the optimization is meant to exclude, such as block rotations.

**Comment by coderbot16** [comment]
Alright. Regarding your point about chests, I think that the inventory is only sent when you open the chest, not when it is loaded. That's why WDL can't save chests you haven't opened. Vanilla actually doesn't send a whole lot of NBT data on chunk load, but I do see your point about inefficient mods.

**Comment by Speiger** [comment]
Yes you are right regarding the vanilla TileEntities, they dont send all TileEntityData over but still plenty.
And mods on the other hand in a lot of cases do. (Reborn mods do especially).

Anyway i can't change this because of mentioned efficiency problems but also because it would take litterly at least twice as much memory to send that stuff over since NBTData requires a String to be send over with instead of just sending the data in order over and read it ordered back.
Especially since i have to send over data for 6 different sides and also some extra data.
