### ISSUE TITLE
Aether Legacy Compat

### ISSUE THREAD

**Issue by robotbrain** [TinyModularThings/IC2Classic#274]
Having ic2 classic copper dust in an electric furnace when loading a world while aether legacy is installed causes a crash.

https://gist.github.com/robotbrain/116cffe0f080d6ed82911fe34e61d211

**Comment by Speiger** [comment]
That log shows no crash with ic2c.
Also did you check if ic2c runs even without Aether?

**Comment by robotbrain** [comment]
https://gist.github.com/robotbrain/5115b1bedc1298733bb35c18a7a53d39
Another crash, reproduced by loading with both mods and trying to shift-click copper dust into an electric furnace. IC2C works perfectly without aether installed.
The
`at ic2.core.item.recipe.entry.RecipeInputItemStack.<init>` bit in the stack trace indicated I should make the issue here

**Comment by robotbrain** [comment]
https://paste.ee/p/ANqhp
And reproduced with only aether legacy and ic2c installed, using latest versions from curseforge of each and current recommended forge

**Comment by Speiger** [comment]
Oh thats because some mod adds a Recipe With a "Null Item" as input. That means the Block they used doesn't have an ItemBlock which means you can not turn it into a Item. Thats not ic2cs fault.
I had also another bugreport that had the same issue but thats basically the mod making hoppers into nothing in its itemform. 
TL:DR Not IC2cs fault. IC2C has higher Security for wrong inputs because else you could make "Void" recipes and ic2cs machines would produce items out of pure nothing because performance improvements would cause that if there is less checks.

**Comment by Chocohead** [comment]
Couldn't you at least log the recipe that was bad if you are going to crash with it anyway? Reduces the amount of wild goose chasing that can ensue with that kind of thing

**Comment by Speiger** [comment]
@Chocohead not easily, but yeah it should be possible.
