### ISSUE TITLE
Reactor track upgrade doesn't seem to work

### ISSUE THREAD

**Issue by Erik3003** [TinyModularThings/IC2Classic#275]
I've tried to automate a reactor with a track upgrade in a machine buffer, but it didn't seem to have any effect ("0 Items found in the reactor to Track", although there are items that are configured to be tracked). 

Switching modes also wasn't documented in the tooltip or the wiki, it took a while to figure out how to switch modes.

The wiki mentions something about linking the upgrade to the reactor by right-clicking it, but that isn't possible, only switches the siding, and likely the cause of the bug.

**Comment by Speiger** [comment]
you need to click it with the side inventory key to bind it.
And yes the upgrade is janky. Its implementation was done at the end of the development ciricle and problems with the usability (only how annoying it is to use) were not made do to being burned out of mc modding because it was a 1 year project.

**Comment by Erik3003** [comment]
Ok, the linking with the reactor worked, it says it's tracking, but it doesn't extract the cooling cell, even when at zero durability. 

I guess I should stick with my Integrated Dynamics system for extracting damaged cells, which is much more complex, but works reliably. 

I suggest removing the reactor tracking upgrade altogether when a new small bugfix patch needs to be released, as fixing it may not be worth the effort (since I'm probably the first person trying to use it).

**Comment by Speiger** [comment]
@Erik3003 it only sucks out the "Durability" items when they are at 90% or more damage. And it only inserts items when the slots required have a missing item.
Also the Upgrade direction needs to face the reactor/chamber from the machine buffer (if that side is not right it wont take/insert it). 
Same goes if the item does not match then it will extract that item too.

Also about other mods doing this. Good luck I made this upgrade so you "Actuall" can automate the "Coolant" options because the "Durability" you see is not the Durability that other mods see. What other mods can see is the "Type" of the coolant cell, not its durability because thats stored in the NBTData under a tag. And there is little to no mods that can say "ReadNBTInteger & Compare" like they do with ItemDamage.

There will be soon a content patch with additions that may or may not address that issue.

I am not happy with that upgrade either but back then everything was a bit more different for me.

**Comment by Speiger** [comment]
well when you bind it to a reactor it takes a snapshot of the layout and then tries to enforce that layout @Erik3003 
thats why it is not working for you in most of the cases.
