### ISSUE TITLE
Non-electric jetpack can't be toggled off

### ISSUE THREAD

**Issue by Erik3003** [TinyModularThings/IC2Classic#277]
The jetpack does still function when toggled off, only the sounds are off.

**Comment by Erik3003** [comment]
Nevermind, I had the electric jetpack still in my baubles, but the sound problem is still present.

**Comment by Speiger** [comment]
@Erik3003 yeah the sound is an issue since the MP sound engine isnt designed to have 2 of the same item type being played at the same type. I might have to split baubles slots & armor slots, but that would be bad on the other hand if you use both slots at the same time.

(And yes IC2 Classic sounds are MP compatible while IC2Exp doesn't have this feature/bug)
