### ISSUE TITLE
Issue adding custom machine recipes following the wiki. [1.12.2-1.1.1.47]

### ISSUE THREAD

**Issue by Electrofried** [TinyModularThings/IC2Classic#279]
I am attempting to add custom extractor recipes,
following the wiki I created the following customMachineRecipes.json 
https://pastebin.com/S2259nE9

However it is not working, latest.log gives the following error:
https://pastebin.com/LNcsTJQw

Am I missing something or doing something incorrectly or is this a bug? 
Thanks for your help, this has been driving me crazy for hours now.

-Electro

**Comment by Electrofried** [comment]
I have also tried without `  "recipeMetadata": {}` as I did see it was listed as optional, however even with that stripped out with the following json:
https://pastebin.com/7jZZcjXQ

I get a NullPointerException as seen here:

https://pastebin.com/KsrumSWd

**Comment by Speiger** [comment]
yeah you didnt read the documentation good enough because all errors you get are because of stuff you missed to implement.
I mean there is "Actual" working examples in the documentation.
My fix for you: Read the example if you want to make sure it works? Copy it? then modify parts? if it crashes look what you changed and why it could crash what the difference is? And if you are then stuck yeah go ahead i am happy to support.
