### ISSUE TITLE
Biofuel Energy Production Not Clear -> Canning recipes not visible in JEI

### ISSUE THREAD

**Issue by AtomicWaffle14** [TinyModularThings/IC2Classic#282]
Biofuel cells don't have a fluid registry and therefore cannot be used in the liquid fuel generator. In the event this is fixed, please make the biofuel cell worth significantly more energy than wood gas cell (or also buff wood gas), due to its high cost. This will make plant energy more viable and fun.

**Comment by Speiger** [comment]
@AtomicWaffle14 because they are used in fuelcans. These are modular Fuel sources that can be put into any "Coalburning" generator and allow to make more efficient generator setups since they only output 500 ticks of fuel at once and next time its needed they are provide another small burst of it.

Also fuelcans are used in the strongest "NonePassive" powersource that exists. The Boiler which produces 160EU once its fully heaten up. (Or a lot more RF if you use the steam somewhere else)

Yes biofuel is not liquid in ic2c but thats because its not a liquid in the first place, this is the solid variant

**Comment by AtomicWaffle14** [comment]
Okay, but how do you make fuel cans? There doesn't seem to be a recipe for them when I check JEI. I'm assuming it would return an empty cell?

Also, is it intentional that the cell itself is consumed in the liquid fuel generator?

**Comment by AtomicWaffle14** [comment]
I figured out how to make the fuel cans by checking the wiki. 

However, it would be nice if there was some way to learn how to use the vacuum canner through JEI recipes. In addition, making it so the Vacuum Canner returns empty cells would be beneficial to automation.

**Comment by Speiger** [comment]
Actually the stuff is visible in JEI. Search for usage on the Finished coalFuel & other fuel cells?
That makes it visible too.
Sadly jei isnt as perfect as i wished and it doesnt show usage on the FuelCan itself.

**Comment by Speiger** [comment]
Yeah it doesnt show the recipes for the possible input.
But the logic itself works fine. You cant just add a "Multiplier" to something that doesnt have fuel.
Will be patched next patch. So that the Canner recipes are clearly visible.
About the tin cells. Sry nothing to do since the recipelist itself doesnt support it but also there is a lot more to calculate with that kind of thing.

(Also lets ignore that you get spammed with tin in ic2c)

**Comment by pmd131** [comment]
It definitely makes sense that adding a return system for tin cells would be hard, but there is one alternative. Why not just skip the step of fuel cells, and put compressed plants (and other fuel cells) directly into the canning machine with the fuel can? 

The step of making a Bio Cell, then a Biofuel Cell, just to turn it into a generic Fuel Can seems kind of pointless. Even if I'm spammed with tin, I feel like I'm fueling my energy system with 33% tin and 66% plants. Doesn't feel like green energy to me, and it breaks the immersion. Eliminating the step wouldn't be very hard to implement, as there's no other use for the fuel cells.

**Comment by AtomicWaffle14** [comment]
The step of making a Bio Cell, then a Biofuel Cell, just to turn it into a generic Fuel Can seems kind of pointless. Even if I'm spammed with tin, I feel like I'm fueling my energy system with 33% tin and 66% plants. Doesn't feel like green energy to me, and it breaks the immersion. Eliminating the step wouldn't be very hard to implement, as there's no other use for the fuel cells.

**Comment by AtomicWaffle14** [comment]
Okay, feel free to take the time you need to brainstorm. Whether its adding a tank to the canning machines and making biofuel into a liquid, some other solution, or nothing at all, I appreciate the time and effort you're putting into this and how quickly you're responding. So thank you!

**Comment by Speiger** [comment]
No problem
