### ISSUE TITLE
Content on 1.7.10

### ISSUE THREAD

**Issue by DrParadox7** [TinyModularThings/IC2Classic#296]
Hello,
Do you plan in the future to still add a little of the new content from 1.10 to 1.7.10? There is a lot missing but not enough to discard the content and performance of 1.7.
I loved the new additions you made especially the new energy generation, crops and the plasma tier. I went as far as trying to decompile and backport it for personal use with little progress so far (not given up yet).

Anyway, thoroughly enjoy your content as it sparked my interest in ic2 once again after Exp killed it and know that in no way I take your work on it for granted. I hope you take this idea in consideration for those of us stuck on 1.7.

**Comment by Speiger** [comment]
well some small features might be ported back if they are not to complex but basically there won't be a big backport from 1.12 to 1.7.10 (1.12 = 1.10.2 port)
On top of that certain performance improvements / features are not really possible do to version limitations (also mod engine limitations that can not be changed do to worldbreaking & ic2exp compat)

i hope that answer is sufficient.

**Comment by DrParadox7** [comment]
I believe the additions of the new crops, new power gen and plasma tier would be enough for 99% of people out there. And on that note, possibly remove RF to EU conversion like in postreleases?

**Comment by Speiger** [comment]
Honestly backports only happens when i have right now a interest in it. (Which isnt the case right now)

On top of that, You only need to ask for upgrades and then you have basically backported the entire mod...

And neither do i have the interest nor the time to do that this month... I have 2 mod patches queued up, loads of work, and my game had no work since almost 8 weeks made on it... 
So backporting is not going to happen.
The version is still getting bugfixes thats sure, but anything extra is not guranteed.

**Comment by DrParadox7** [comment]
I understand that clearly. I hope some of it makes its way there if you ever find the interest to.
I'll be keeping my fingers crossed. 👍
