### ISSUE TITLE
Even More Mysterious Tea (not a bug, just an explanation request)

### ISSUE THREAD

**Issue by esotericdesign** [TinyModularThings/IC2Classic#298]
So I managed to get all the crops except Aurelia and Tea. I'm trying to crossbreed Coffee with itself, I looked up the attributes and tried to experiment in creative with Hops+Coffee combo (oh the great almighty Overgrowth Fertilizer!), I tried to switch my Cropnalyzer to Breeding mode... still can't find out how to obtain it in survival. Some guides say there is tea in HarvestCraft, which I don't have, and I fail to learn from the local wiki, for it has everything but recommended breeding combos.

Guess I have to ask for help here. How exactly do I obtain Tea in Survival, if it's possible? I'm at 1.7.10, mod version 1.2.1.8

**Comment by Speiger** [comment]
In 1.7.10 you have to install the crop breeding plugin since that was where it was created, and then its basically just requiring a cropanalyzer. Why not integrate it? Because it works with IC2Classic & Exp and it would not be fair for the GT5 users to remove it. Especially since it gets special support from addons already.

Note that the Wiki is around 80-90% accurate on features since its based on 1.10.2

**Comment by Speiger** [comment]
Closing. Because yeah not going to add to much content here.
