### ISSUE TITLE
[Suggestion] Add More Advanced Tools & Armors

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#301]
Hello, 

Since GraviSuite is not compatible with IC2Classic, many of us (including me) miss the tools and armors, which adds this wonderful mod.
I wanted to suggest to add following items into IC2Classic:

Misc:
1. Superconductor Cover;
2. Superconductor;
3. Cooling Core;
4. Gravitation Engine.

Armor:

1. Advanced Electric Jetpack (see recipe below):
    - 1.000.000 EU;
    - Can charge items; 
    - Ability to fly (with regular HoverMode) - Enable/Disable Fly by "Toggle Key".
2. Advanced NanoSuit BodyArmor (regular GS recipe):
    - 1.000.000 EU;  
    - Can charge items;
    - Ability to fly (with regular HoverMode) - Enable/Disable Fly by "Toggle Key".
3. QuantumGravi Bodyarmor (regular GS recipe): 
    - 10.000.000 EU;
    - Can charge items;
    - Creative fly (Extreme HoverMode) - Enable/Disable Fly by "Toggle Key".
4. Ultimate Lappack (see recipe below): 
    - 10.000.000 EU;  
    - Can charge items.

Tools:
1. Advanced Diamond Drill (regular GS recipe): 
    - 15.000 EU; 
    - Modes: Normal / 3x3x1 mining mode (switching by ModeSwitchKey); 
    - x2(?) more effective than Diamond Drill;
2. Advanced Chainsaw (regular GS recipe): 
    - 15.000 EU; 
    - x2(?) effective than Chainsaw.
3. GraviTool [it is not a "must have" one, but eh] (regular GS recipe):
    - 100.000 EU 
    - Modes: HOE, WRENCH, TREETAP (switching by ModeSwitchKey).

![image](https://user-images.githubusercontent.com/25727222/52533251-ce5b8180-2d39-11e9-8fcd-a6517d3ddb91.png) - Advanced Electric Jetpack

![image](https://user-images.githubusercontent.com/25727222/52533261-0793f180-2d3a-11e9-9ac5-4511f6cd8662.png) - Ultimate Lappack

I hope I do not ask too much.
Let me know what do you think about this.

Thanks!

**Comment by Speiger** [comment]
well this is a large request. Let me answer those bit by bit:
I assume the first 4 items are crafting components, because else they make no sense.

- Advanced Electric Jetpack: Becomes useless because nuclear Jetpack starts with 1Million EU capacity and that can grow up to 50-100Million EU. Not instant i know but its potential power it can produce.

- Advanced NanoSuit BodyArmor: Nano Armor gets no Abilities at all, its the first tier with protection only features so even upgraded versions in classic at least go directly to Quantum Armor.

- QuantumGravi Bodyarmor: Besides charge items, already a thing. 
Personally i am not so much of the fan that armor can at the same time also charge items as it protects, then the entire shielding logic has to be updated to match that kind of thing where it has a shieldgenerator which limits the output. To solve that problem. Baubles is your solution since the components like charging armor etc can get put into there. Thats my tradeOff.

- Ultimate Lappack: Yes i can see the point, after tier 3 there should be a tier 4 backpack especially with plasma stuff, that it should also require. I would maybe increase the capacity quite a bit though.

- Advanced Diamond Drill: Oh you are not the first one to ask for 3x3 mining, and you wont be the last one, if my memory accurse right i had at least 50 request in total for it. And my answer was always Not going to happen. Because how do you balance 3x3 mining properly? Tinnkers construct has a massive balancing problem where for mining (not building) a hammer is to overpowered. If i ever implement a 3x3 mode drill it will at max get 3 uses of power that will also scale with tier 4 that means it will maybe have 100kEU but per mining you pay 33kEU. Otherwise it becomes way to overpowered.
Now a side note: I implemented Enchantment support for Drill & Chainsaws which will increase/decrease speed and powercost so you can based on enchantments already customize your tool in other ways.
Unbreaking = -10% power consumtion, Efficiency = +15% power consumtion. Ofc stacking per level.
This feature basically negates that requirement. Also the drill is able with a scanner to probe the ground if there is actually something of interest nearby. (Adjusts based on the scanner).

- Advanced Chainsaw: Again like drill pointless because of enchantments which allow to control the cost of power and speed dynamically.

- GraviTool: Nah, straight nah... Especially since these tools have special abilities each which make them more useful. Especially the wrench has now 3 tiers + optional 4th tier that is useless with classic only but with addons might come useful.


Yes I am fully aware that I just said no to basically everything except the energyPack, which is actually something concidered.
But TL:DR you ask for the gravity suit addon that just came out for classic ([Link](https://github.com/Trinsdar/Gravisuit-Classic-Edition/releases)) to be integrated. First of all i dont like Gravity suit so its not going in, i decided against that a long time ago (1.7.10), it is a ok addon but not matching with IC2Classics idea.

On top of that you have never played with IC2Classic before because then you knew all these things i just posted to you and would have moved the request a bit differently to have maybe IC2Classics adjusted components in these suggested recipes.
I give you that you read the wiki since "Extreme Hovermode" is a thing. Though the word choice could have been random luck for a match but i give you the benefit of the doubt.

Anyway since gravity suit and a couple other addons are being ported by Trinsdar you can be happy that it already exists.
He also ported AdvSolar Panels, but a warning the balancment is based around Compact solars so you still need to craft 512Solar Panels + Plasma stuff before  you can get the highest tier.

Anyway thanks for the suggestion I hope I was not to mean, but I need to clearify my stand on this too correctly.

I hope you have fun playing with IC2C, if you have more suggestions you can report them here and we go through it.

**Comment by CrossVas** [comment]
So first at all, thank you for your answer and a big one for GSClassic's link.

**Comment by CrossVas** [comment]
@Speiger actually you are right. All of this content become useless when you have Baubles installed, but I always miss an advanced way of mining different from regular 1*1 one. That's why I suggested these items. Now I enjoy playing with gravisuit classic which satisfied me entirely.
Keep up this great mod!
