### ISSUE TITLE
[Question] Flying Speed

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#303]
I'm wondering about a way to increase my flying speed, because IC2C's Jetpacks are "very fast" on forward moving. 

The only thing I've found is to wear QLeggs, sprint and fly -> you will fly with a decent speed.
Although, when you want to go up your speed gets dropped.

If there is no way to increase forward Fly Speed, then I would like to suggest to add ability to sprint when flying.  

Thanks.

**Comment by Speiger** [comment]
That is sadly not so easy to implement since the jetpack actually does not interact with the player movement at all. In regards to WASD at least. The only thing that the Jetpack does is move you upwards and forwards based on the current thrust. That on the other hand is just a multiplier on existing movement. Hence why you can fly straight up and down instead of slowly forward.

Its a unqiue way of causing to fly. On the other hand its also somewhat more realistic (even so i hate that arguement) since once a player flies it is not easy to change momentum unless you are using a outside force.

I hope that answers your question.
