### ISSUE TITLE
[1.7.10] Steam Reactor is out of order

### ISSUE THREAD

**Issue by esotericdesign** [TinyModularThings/IC2Classic#304]
The local wiki says that it needs a liquid transportation mod to work. I have Pressure Pipes, which does have an automatic transportation way. I built two tanks, connected it to the Reactor, filled the input one with water, inserted a Uranium Cell and a Steam Vent... the latter just dies in a few seconds, no steam produced, no water pumped... how do I make it work?

tl;dr: Steam Reactor seems to have no tanks, therefore can't generate anything. no side inventory, either

**Comment by Speiger** [comment]
![2019-03-05_14 20 30](https://user-images.githubusercontent.com/2556269/53808392-607a3280-3f52-11e9-9d6c-7bd6d792f6ae.png)
I think something in your theory seems wrong. I think you did not setup the reactor properly. Because this test with vanilla IC2C can do it easily. And by the way the way Vanilla IC2C does it is the same way as any other mod does it too with fluids.

I think your reactor setup was not done properly or you overheat your setup to much that the vents can not keep up since they work better the hotter they get so they work at best when they are at 0.5% Durability. (Tooltips show that by the way)

Here is the reactor setup that i used:
```
igdjo2030p14oi6okdhbdl85b7t5ptz0uuirj
```
Just copy that go to a reactor planner and hit import it will know exactly what i build there.

**Comment by Speiger** [comment]
You can by the way send me your setup through the reactor planner as well.
![2019-03-05_14 28 36](https://user-images.githubusercontent.com/2556269/53808604-fb730c80-3f52-11e9-9a5d-12719c895622.png)
By the way this is how it looks like if the reactor can not get the steam away and if the reactor is full of steam the steamvents fail and dont exhaust heat and destroy themselves if you are unlucky.

**Comment by esotericdesign** [comment]
Thanks, got it now.
The thing was that input/output blocks (those under the steam chambers) only provided flow from the bottom, though outputs inside the tanks show sideways connecton as a correct way either. Had to put pipes in use instead of a tight block-to-block setup.
![2019-03-06_02 23 38](https://user-images.githubusercontent.com/40729240/53844804-fac09180-3fb7-11e9-966a-4430be87897e.png)

Tried this setup btw
1uh88jtu4sjj8a8rsnbu8kzv1sns0479fdlcmkd8oq9hf9b

Also, is there a way to check the inner reactor tanks? Other than WAILA-like mods, I mean.
I remember IC2 Exp GUI laid them out like Nintendo Switch controllers.
I have Nuclear Control 2, but its panels show up the same data as for Heat Reactor, i.e. current temp, melting temp, energy production rate etc.

**Comment by Speiger** [comment]
I almost just closed the stuff because of the IC2Exp textures... Lucky that I read what you said and tested the setup.

As of right now there is not really a way to see the tanks contents within ic2c itself. Other mods may be able to see the contents since both tanks are listed under the getTanks function for reading.
