### ISSUE TITLE
Glass fibre cables disconnecting

### ISSUE THREAD

**Issue by Joomzy** [TinyModularThings/IC2Classic#320]
I've had this issue for a while and it's very random to reproduce. Sometimes all of my glass fibre cables disconnect from eachother. Sometimes only a certain part of my base, sometimes the entire base, sometimes no cables get disconnected.

Today I restarted my server, logged in and all of the cables were disconnected as small little stumps, no power went through this. After restarting the server this fixed this issue this time.
This can also rarely occur when travelling from far distances or from dimension to dimension.

Also sometimes it just disconnects at AE2's Energy Acceptor. I didn't take a screenshot when this happened but I'll give a sloppy example of how it looks when I say they are all disconnected like stubs.
![image](https://user-images.githubusercontent.com/14014739/58385661-33d73380-7ff4-11e9-82aa-6ea632a32f6f.png) Like this only closer together. I am running build 1.5.4.2 as there is no newer build I decided to open a ticket.

**Comment by Speiger** [comment]
Yeah ic2c uses its own networking system, it could be that the data was not synchorinzed properly since its really random it could be racecondition where my code runs faster then minecrafts which could technically cause this issue. Its only a visual glitch not a server  glitch. Reloading that chunk usually fixes it.

But i changed a couple things within the cable that will be out next patch. The patch is done i am just providing the addon devs with a bit of time to port their addons because this patch actually breaks every ic2c compatible addon that uses core classes because 1 thing changed.

Patch is planned to be released on monday.

**Comment by Joomzy** [comment]
That's awesome, totally unrelated to this ticket but as a question. In the past there used to be a forcefield mod for IC(2) We're talking a lot of years ago, is this still available anywhere as add-on or in general able to be used in IC2C?

**Comment by Speiger** [comment]
I don't know if there is a force field mod, if there is and it is made by Chocohead then its not compatible for sure, if not then you have to try it out.
IC2C has that one not implemented.

**Comment by Joomzy** [comment]
Alright, thank you for the help.
