### ISSUE TITLE
Possibly update IC2 API?

### ISSUE THREAD

**Issue by turbodiesel4598** [TinyModularThings/IC2Classic#325]
Hey there!

I recently had a [crash report](https://pastebin.com/fYx0ysmZ) posted to the NuclearCraft repo (https://github.com/turbodiesel4598/NuclearCraft/issues/526) related to what I think is the fact that IC2C is using an old version of the IC2 API. Later versions contain new classes such as an interface used to highlight armor types as radiation-protective.

Would it be possible to update the API version to prevent these crashes? Thanks in advance :)

**Comment by Speiger** [comment]
Ehhh IC2C has already a Hazmatsuit API
https://github.com/TinyModularThings/IC2Classic/blob/master/src/main/java/ic2/api/classic/item/IHazmatSuit.java
So not anytime soon i will update ic2exp api since the latest patch just came out and now there is a cooldown.
(A reason why i dislike forges API because you can not set "Exclude if Mod Present")

**Comment by turbodiesel4598** [comment]
Oh, in that case they updated the interface - that method was renamed and there are a couple of new methods.

**Comment by Speiger** [comment]
Yeah IC2C has a lot of Interfaces that Exp is missing, TheUpgradeAPI isnt supported from them because i have my own, and from what this API looks like that interface won't be supported in classic.

**Comment by turbodiesel4598** [comment]
No worries - thanks for replying so fast!

**Comment by Speiger** [comment]
@turbodiesel4598 latest patch (hotfix) had also the API update. Note: There is a couple changes that are not take over because they have IC2Exp dependency.
