### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Joomzy** [TinyModularThings/IC2Classic#326]
Unsure what this means or if it's an issue on my end or IC2C but since it told me to report it I did it anyway. Not sure if you could use more info on this or not, if so please do ask ^^
http://prntscr.com/nvj5zm

**Comment by Speiger** [comment]
@Joomzy eh this is a false report, Forges WorldGen Cascade is not properly done, it means that a mod would load another chunk during worldgen. It could have been IC2Classic, but the chance that it is actually that are rather low since ic2c has small worldgen nodes that try to be at the center of chunks.

Since ChunkPregen told me how unrealyable it is (blaming mods who do not even have worldgen at all) I am not trusting that kind of report.

Thanks for reporting it though.

**Comment by Joomzy** [comment]
Fair enough, thanks for the info. I don't experience issues with it, it just seems to pop up frequently and decided to give it a whirl.
