### ISSUE TITLE
Addon Compat Testing (Please no adding new ones)

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#33]
I've tested all the addons in Tekkit Classic (I'll test other ones afterwards if I've got time) and these are the results:
* Advanced Machines (Immibis) - Works, E-net connections very unstable. The advanced machines in classic are much better than using this.
* Advanced Machines (Atomic Striker's) - Crash,  can't be fixed
* Advanced Repulsion Systems - Works fine (might duplicate cows, or I might be insane)
* Advanced Solars - Apart from a few item.null.names from experimental items it works fine. Might want to remove it's Uranium Ingots though, as IC2 Classic's Refined Uranium is what it replaced
* Advanced Power Management - Works, but it riddled with it's own bugs: https://github.com/xbony2/Advanced-Power-Management-2/issues/2
* Combo Armours - Crash, can't be fixed from the looks of things
* Compact Solars - Works fine
* ElectricalAddition - Works, but has a max input voltage of 0 EU/t (see forum thread).
* Gravitation Suite - Ignoring some localisation issues, works fine
* IC2 Backpack HUD - Works fine
* IHL - Crash, doesn't look like it will be fixed
* Iridium Mod - Loads fine, but iridium can't be used
* Nuclear Control 2 - Seems to work fine for normal reactors, still have to try with steam ones
* Power Converters (Portablejim's) - Works fine, has it's own bug with the consumers having 4x less the voltage than they should: https://github.com/portablejim/PowerConverters/issues/34
* Power Utils - Works fine
* Ztech - Crash, same as AtomicStrker's Advanced Machines

Still to be tested:
* E-net Bridge - If it works I'd be amazed
* Tech Reborn or whatever that GT4 clone is
* GregTech 5 Unoffical
* GregTech 6

Might test:
* Armour and Tool Status HUD
* Electro-Magic Tools
* Turbo (needed for next 2 mods)
* IC2 Tweaks
* Biomaterials
* CarbonTech
* VoidTech

**Comment by Speiger** [comment]
Ok thanks Chocohead.
I will take care of that and fix that as soon as possible, if that is possible. (Would be perfect if you can give links to the crashreports/logs, it would decrease the testing time perfectly)


The mod Armor and Tool Status hud you can delete from your list,
it will run. But no Classic support because its an exp thing.
And to install that compatiblity (through the api) makes no sence...
At least at my opinien. If your armor gets low (because of no eu) you nodest that before you will die anyway.

**Comment by Speiger** [comment]
Vacuum canner works not because the RecipeList is a fake and the original canner has no recipe list..
Electrial additions ok work on it need only TileEntityClassNames and the Original Max Voltage... I checkt it afterwards and it should be fixed according to the sourcecode. 
Ok that should be everything i close that issue because from my side there is nothing to fix at the moment. (At least what i am able todo by my own... Everything else needs to be done by the moders itself or with me together)

**Comment by Speiger** [comment]
Reopening for public view so they can follow the status easy.

**Comment by Carbon-Ghost** [comment]
Current status with some of these mods + some other mods : 

-There was an old bug with ARS which made power infinite with IC2 classic, should be fixed now, gonna test when I have time ^.^

-Mekanism 7 works like a charm, no problems encountered, works just as fine as experimental, if not better. 
-RC E-net sometimes bugs with the RC steam turbine, might be the same with the RC eu to charge energy converter, so far I only tested in always loaded chunks, gonna need to see if there isn't some bugs with it....
-Project E : Suprisingly enough, it automatically added EMC to uranium, which doesn't seem OD, but even so, it's internal EMC calculator unfortunately failed for registering empty cells EMC, but once you do add EMC to them, it auto creates EMC for water and lava cells, also, refined iron have EMC :D
-AE2 works perfectly except P2P tunnels, but meh, I disable them anyway ;P

**Comment by Speiger** [comment]
RC: Is a EnergyNet bug because he uses a lot of IMetadelegated TileEntities which the EnergyNet do not really like...
Also unloader & Loader are buggy with classic because CJ uses for almost everything a IMetadelegate and he did not adjust his parts to the new api.

AE: I think that the parts are IMetadelegate so same as railcraft...

**Comment by Carbon-Ghost** [comment]
Ah, well, sad ;( Also, ARS Works perfectly now ;D

**Comment by BBoldt** [comment]
Not sure if this is the right place to post this, but since it's technically a compatibility issue, I will post here. Bluepower apparently has some IC2 integration (not sure what) which results in this crash while loading:

https://gist.github.com/a57b1f2236fa8b975fea

**Comment by Speiger** [comment]
@BBoldt yeah its my fault that this happens... I need to add a recipe list to the washing machine (fake list) thanks for the bugreport i will fix that so that the next version has no longer problems with anymore...

**Comment by Speiger** [comment]
fixed by the way...

**Comment by FnordMan** [comment]
Not sure if this would go here or somewhere else. 
The Universal Cables in Mekanism v8 don't work with IC2 classic, no power gets moved to or from power producers and machines/storage.

**Comment by Speiger** [comment]
I checked it. And it should work normally but they do not really use the IC2 API how they should be...
A lot of Mistakes are made in their code...
They made it themselves way harder then the needed..

**Comment by Carbon-Ghost** [comment]
I remember Mek 7 working perfectly with IC2 classic though...

**Comment by FnordMan** [comment]
Sounds like it's an issue for them to fix then. Looked around on their issues page, didn't see an open issue for this problem so I made a new one.

**Comment by Speiger** [comment]
Closing with 1.7.10
