### ISSUE TITLE
[Suggestion] Portable Generator?

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#330]
I think it would be neat to have some form of portable generator, which consumes fuel from fuel cans to generate EU while in your hand/off-hand. Possibly it could also only provide power to the hand/off-hand slot?

A possible upgrade could be a nuclear version, which has a small reactor inside it like the nuclear jetpack, but is turned on/off manually and provides EU to whatever is in your hand (if anything)

**Comment by Speiger** [comment]
the idea was already thought of once during the 1.10.2 version but was never implemented because the way how the Inventory Energy Transfer works is not really making this a good idea.
Inbalance is a really big problem. Because the way how ic2c shares energy in your inventory makes it also work with armor etc.
