### ISSUE TITLE
Wave Generator Config/Wave Generator Feels Really, Really Powerful

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#333]
I feel like the Wave Generator is a bit OP with how much EU it produces, especially considering it is capable of producing energy anywhere if you build a 50-block long track of water. I feel like it'd be better if its energy production was cut by a third, probably also significantly more of a cut if the generator is not in a Beach, Ocean, or similar biome.

Also, I decided to check the Ocean generator since I remembered it being similar in the old Advanced Generators mod, and I feel like the same thing applies, except even more so. 100 eu/t constantly for free sounds like WAY too much, even for something that is limited only to deep ocean biomes. It could easily be cut to a quarter, or even by 10, and still be very useful and worth making.

**Comment by Speiger** [comment]
You could say the same about the bio loop that you can create in ic2c. That thing produces EU for free to and not very little either.
The issue is if i make "Solar Power" the only solution to endgame power requirements then they will start focusing that. 
But yes you are right the config for these generators are missing. That is at least something i could do.
About balancing, my focus is get people away from solar because that is what is stuck in mind thanks to the addons. (Guess why the HV Solar Panel is so f....ing expensive)

**Comment by Speiger** [comment]
Oh next patch should come out (Hopefully) by the end of this week or starting next week.

**Comment by abculatter2** [comment]
Solar is already very resource intensive for what it produces, which makes it great for a dead simple but very expensive renewable energy source. You don't need to make the other generators 10x more powerful then solars just to make them viable, as solars already have downsides, you just need to make the other options more resource efficient per EU, or make them provide some other form of benefit such as consistent power output.

**Comment by Speiger** [comment]
Done config added.
