### ISSUE TITLE
How to charge Nuclear quantumsuit bodyjetplate?

### ISSUE THREAD

**Issue by Liviflame** [TinyModularThings/IC2Classic#350]
I cant seem to find out how or where to charge it, is there a key for a gui? is there some sort of machine that i need to use?

**Comment by Speiger** [comment]
Assuming you dont play 1.10.2 or newer (because tooltips)
it should be the "InvKey" + rightclick in your hand to see the reactor.

Also nuclear items can only be charged from their Internal Reactor for the reason that the uranium produces so much power and gets so many buffs that there has to be a downside.

**Comment by Liviflame** [comment]
playing on 1.12.2 in tekxit 3, Theres no tooltip for it, but thank you!

**Comment by Liviflame** [comment]
What is invkey? like my personal inventory, the side inventory? I'm right-clicking with it in my hand, which it auto equips it to my chest, I'm doing it with an empty hand which results in nothing.

**Comment by Speiger** [comment]
@Liviflame there should be a tooltip on the item that says "press ctrl/shift/alt for infos"

Let me check the keybindings. Oh its just sneak click ^^"

**Comment by Liviflame** [comment]
how did i not notice that what the heck thank you so much i love you no homo ok thanks bye

**Comment by natesteelers12** [comment]
what do I use to charge the nuclear quantumsuit bodyjetplate?

**Comment by natesteelers12** [comment]
like is it an ore that I smelt or is it a charging starion?
