### ISSUE TITLE
JEI recipes don't fit their boxes

### ISSUE THREAD

**Issue by DaedalusGame** [TinyModularThings/IC2Classic#353]
The following recipe categories have recipes that don't fit the allocated box:

Liquid Fuel Generator
![javaw_iguJYdRdeh](https://user-images.githubusercontent.com/9559216/63052860-b0d1c500-bee0-11e9-8eed-2344ca200b7d.png)
Electrolyzer
![javaw_N8H85tnyvw](https://user-images.githubusercontent.com/9559216/63052861-b0d1c500-bee0-11e9-9043-d174f2ad27d7.png)
Canning Machine
![javaw_lriXkXb3ac](https://user-images.githubusercontent.com/9559216/63052863-b0d1c500-bee0-11e9-8773-0f50e55e84ae.png)
Crafting Table
![javaw_Y1Ugwrjikk](https://user-images.githubusercontent.com/9559216/63052864-b0d1c500-bee0-11e9-9a7d-dc69e81fc9a4.png)
Recycler
![javaw_syhVVi0yGE](https://user-images.githubusercontent.com/9559216/63052866-b16a5b80-bee0-11e9-91bf-89fa953540d3.png)

**Comment by Speiger** [comment]
Yeah thanks. May be patched with the next patch.

**Comment by Speiger** [comment]
Not going to be patched since IC2Classic development is on a ForgeVersion that is outdated.
And it will stay there until the next gamebreaking forge patch comes out if I dont update.
So I can not even see these lines because JEI enforces latest forge versions which I won't support.
And my version does not have this feature.
Also since that is Dynamic I can not even control the "Crafting" one because that is JEI Internal stuff.
Sorry
