### ISSUE TITLE
Config line addition for certain villager trades

### ISSUE THREAD

**Issue by Ad-Blokker** [TinyModularThings/IC2Classic#355]
Hello guys,

Great project so far. Just one suggestion. Would like to see a config line addition to disable the UU matter and Quantum accumulator trades. Maybe a config line to disable certain trades if you want to do that for balancing sake. Otherwise customizing the trades would be nice so you can choose/balance yourself.

I know you can outright disable all of these villagers but that is a bit rigorous for me.

Thanks in advance!

**Comment by Ad-Blokker** [comment]
#354 Also talks about this

**Comment by LGCMcLovin** [comment]
Please add this, kind of game breaking for players to get 64UU-matter for 1 emerald!

**Comment by RawrMaoster** [comment]
Agreed, please address this. Im tired of hearing about the broken UU-Matter issue plaguing the server.

**Comment by Speiger** [comment]
I can add this (a config for greg villagers only (that much i am willing to do)) but again I can not apply the change after you got the villager. You need to kill it to remove the trades since vanilla stores them in the villagers NBTData. (And no i am not touching villagers nbtdata)

For now disable ic2c villagers if you dont like that or kill all gregs xD

**Comment by Speiger** [comment]
Implement blame greg config.

**Comment by emirso** [comment]
Coming here from 2021, where is the config file I cant seem to locate to close gregs

**Comment by Speiger** [comment]
"enableGreg"
