### ISSUE TITLE
Game crashed during startup

### ISSUE THREAD

**Issue by drenough** [TinyModularThings/IC2Classic#370]
I'm using version: IC2Classic 1.12-1.5.4.4

It started crashing when I use via CraftTweaker zen script for change every iron ingots to iron plates.

Crash log here: https://pastebin.com/WRsjubwy

**Comment by Speiger** [comment]
the issue is that logs do not have a output for their crafting recipe. 
This is a ic2c issue that it returns the wrong data and causes a crash but its triggered by registering a log that does not have a recipe to planks. (Using the recipe list for the saw mill to find out which log has which plank as a output and duplicate the recipe)

**Comment by Speiger** [comment]
will be fixed in the next version

**Comment by Speiger** [comment]
fixed
