### ISSUE TITLE
What item do i use to charge my nuclear quantumsuit body jetplate?

### ISSUE THREAD

**Issue by natesteelers12** [TinyModularThings/IC2Classic#405]

**Comment by natesteelers12** [comment]
I'm kinda new to this mod and need some help on how to use it

**Comment by Speiger** [comment]
@natesteelers12 nuclear jetplates have a nuclear reactor that you can access via a keybind (should be in the tooltip) since it has a reactor its not chargeable by any other means.
You need a reactor setup for it. The reactor will autoenable if there is think less then 25-30% charge in the armor and stop running if the armor is full.
Note: The reactor in your armor "CAN EXPLODE" and it will remove itself too before that that means the explosion can be treated as missing 1 armor piece. (And you will be in the dead center of the explosion)
I suggest you use the reactor planner to test setups to ensure you dont blow yourself up.

**Comment by natesteelers12** [comment]
Do you know what items or blocks I need for the nuclear Reactor to put in the piece of armor?

**Comment by natesteelers12** [comment]
Like what do I put inside it so the EU goes up

**Comment by PrincessOfEvil** [comment]
Same things you put in a normal reactor. Just use a reactor planner, jeez.

**Comment by Speiger** [comment]
@natesteelers12 https://github.com/TinyModularThings/IC2Classic/wiki/Nuclear-Reactor
