### ISSUE TITLE
Nano-Saber with Shield.

### ISSUE THREAD

**Issue by delta4873** [TinyModularThings/IC2Classic#406]
Currently using shields with the Nano-Saber is impossible, blocking instead rapidly turns the saber on and off. In the original blocking with the sword wasn't implemented due to balance reasons, but with the addition of the Nano-Shield, being able to use both would make sense.

**Comment by Speiger** [comment]
Kinda a bug kinda intendet. How do you want to turn on and off the nanosaber? Usually you need a quick reaction time to turn it on. You don't want to be stuck turning it on. And you don't want to keep it on all the time because it uses passivly power to stay active. And not a small amount I might add.

**Comment by delta4873** [comment]
All I can think of is making a separate keybind to activate the saber, like the jetpack. That might be a bit clunky though.

**Comment by Speiger** [comment]
The honest best solution have 2 seperate keybindings for "activating" and "deactivating" it.
Activating it would be rightclick and deactivating would be rightclick + something different
that way it can no longer spam on and off.

Though I doubt that I will implement it that way.

**Comment by delta4873** [comment]
That would probably work best, the deactivate would work the same as switching modes with the jetoack
