### ISSUE TITLE
Nuclear Reactor stacksize issue

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [TinyModularThings/IC2Classic#408]
If something tries to push a stack with more than 1 rod in one call (like AE2 export bus with acceleration cards), the reactor will accept it all in one slot.
https://yurie.thigh-high.club/dbj3o4rq.mp4
https://yurie.thigh-high.club/hxs4hpui.mp4

IC2Classic 1.12-1.5.4.5

**Comment by Speiger** [comment]
@YuRaNnNzZZ yes but this seems to be a AE2 issue since they seem to not take the max "item" stacksize into account when exporting things. The reactor has to support more then 1 item stacksize because there is stackable items for the reactor. 

If you can replicate it in a vanilla chest then its a AE2 Bug not a IC2C bug

**Comment by YuRaNnNzZZ** [comment]
Vanilla chest accepts stacks as expected, 1 item per 1 slot.
https://yurie.thigh-high.club/7mhjcgio.mp4

**Comment by Speiger** [comment]
Ok I will look into it once i am coding on ic2c again.
No real eta right now but any issue that is here will get fixed the moment i work on the project again.

**Comment by Speiger** [comment]
Should be fixed.
