### ISSUE TITLE
Cubic Chunks Compatibility Issue, No wind

### ISSUE THREAD

**Issue by border999** [TinyModularThings/IC2Classic#413]
I posting this simply to point out an issue exists but that I don't know where the fault lies between the two mods about it. In a cubic chunks world, I can't appear to find anywhere with a wind speed above 0.

**Comment by Speiger** [comment]
Its a wonder that you didn't have other issues.
Because the code only supports Y level 255 max. Because I am using a function that saves ram but limits the yaxis data.

You might be using the realistic wind simulation and the simulation is floating around way to high so there is no air streams left.
Just turn of realistic wind simulation and it is applied globally everywhere in the world.

**Comment by border999** [comment]
you have realistic wind in the IC2 config?

**Comment by Speiger** [comment]
yep

**Comment by border999** [comment]
I'm not finding that bit, mind sending a copy of the config you have then? I want to compare and see if I'm missing anything.

**Comment by Speiger** [comment]
What Minecraft Version do you use?
It is only in 1.10.2 or newer. (The realistic Wind Simulation)
```
    # enables the Realistic Wind Simulator. Makes the Classic Windmills anywhere efficent but less worth
    B:useRealisticWind=false
```

**Comment by border999** [comment]
hmm, might need to regenerate my IC2 config
