### ISSUE TITLE
Electric enchanter recipe is not oredicted

### ISSUE THREAD

**Issue by DBotThePony** [TinyModularThings/IC2Classic#417]
![javaw_137RHenfHl](https://user-images.githubusercontent.com/6339511/84283169-e2e59f00-ab64-11ea-8c96-87d25389e848.png)
![javaw_1HcXBkyIbi](https://user-images.githubusercontent.com/6339511/84283241-f85ac900-ab64-11ea-95c7-7a73951f8080.png)

**Comment by Speiger** [comment]
Not a bug.
I can not make everything "oredict". Thats why mods like Crafttweaker exist.

**Comment by DBotThePony** [comment]
then why oredict even exist in forge if modders don't use it?

**Comment by YuRaNnNzZZ** [comment]
While vanilla bookshelves are not oredicted by default, it would be great to have support for oredicted bookshelves anyway.

**Comment by Speiger** [comment]
@DBotThePony 
First of all. You are starting to get annoying. If you have a bugreport, that's fine. If you have a feature request. That's fine. But Accept that it is still the work I have to put into the mod. If I don't want to do that then that's my choice.

Second: You seem to think oredict is the solution to everything? No. It has some massive issues. Adding oredict to everything is not a SOLUTION. 
- 1: It has a performance hit to recipe checking. Because recipes get a lot more complex, because oredict isn't Optimized AT ALL. 
- 2: Adding Oredict to everything can have balance problems as well. (Why do you think ic2cs obsidian dust isn't compatible to any other mods obsidian dust)
- 3: OreDict is a means to make interactions with other mods easier. It is not a Requirement. How much oredict is a thing is up to a modder.

While your request is valid to add support to bookshelves I would like you to take a example of @YuRaNnNzZZ and also respect my answer that I am not adding that.
