### ISSUE TITLE
trying to fix #433 not only didn't fix it, but now cactus or sand won't fit in an electric furnace either, and I assume other things

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#444]
related issue: #433

**Comment by Speiger** [comment]
Yeah saw your comment in the old one.
I can fix the sand option easily by reverting the fix, but for binnis stuff i request exact testing why it is not working, because i have no idea why it is happening.

**Comment by flameoguy** [comment]
I just tested this bug on a creative world with a variety of smeltable vanilla items and a few nonsmeltable IC2 items. None of the items in my inventory will fit in the top slot of an electric furnace. This problem does not occur when using the iron furnace. My guess is that the electric/induction furnaces will only allow certain modded recipes, such as ore dusts to be smelted.

![2020-10-21_16 04 26](https://user-images.githubusercontent.com/12553002/96776543-283d9700-13b7-11eb-8a56-028f891678ea.png)

**Comment by Speiger** [comment]
@flameoguy the issue is that the new check is different and has more flaws in that regard.
Iron furnaces uses a different recipe list (Furnace RecipeList)
while Electric Furnaces use a Cloned RecipeList that clones recipes on the first request.
My guess is that #433 is a to late addition of furnace recipes why that isn't captured. Or that the recipe requires special data.
I will revert the fix attempt and that should fix most of it. But I will wait until @Trinsdar or someone else brings me info on how to fix binnis side if at all possible. Because I have no clue and can not really test it.

**Comment by Speiger** [comment]
Fixed bugged vanilla recipes, hopefully binnis too. Note: Furnace RecipeList no longer supports NBT!
