### ISSUE TITLE
Mining Drill cannot make dirt path

### ISSUE THREAD

**Issue by Maoman1** [TinyModularThings/IC2Classic#479]
Shovels can right click on dirt to make dirt path. Mining drills cannot. A minor thing, but it's important to me since I have a mod which increases running speed on dirt path blocks.

**Comment by Speiger** [comment]
@Maoman1 how would a drill make a path? I would argue that the drill would make farmland since it does not flatten an area but breaks it apart in a way hoes would do it.

**Comment by Maoman1** [comment]
I had a long day at work and am having a hard time wording this in a way that doesn't make me sound like an ass so please just take my word when I say I'm not angry and I do not mean to be rude with this.

Removing functionality that is pre-existing in the vanilla game from a tool which is supposed to not only emulate that tool but to be a superior replacement for that tool simply for the sake of "realism" in a game like this is a hard pass from me. In my opinion it is ridiculous to be required to continue using shovels for one simple task despite having an advanced technological marvel of a borderline magical super drill in my hands.

**Comment by Speiger** [comment]
@Maoman1 you are not rude.
And yes, realism in such a game makes not that much sense, I can agree on that. But here we are in a mod that is going closer to realism then the game itself, I think some "realism" rules can apply here.

Now why the drill can't do neither is simply because it already has a lot of functionality (even rightclick based) and it can just conflict with a lot of things.

And that comes "after" the "lore".

Also a pickaxe usually is used with a "offhand" usecase, torches, and while you may not use it, i know enough people that do.
Offhand torches is the first example that comes to mind.

If it were such a cut and dry problem, like you suggest, I would have already solved that problem, but it isn't.

And while the drill is effectively a shovel/pickaxe in functionality, it isn't a pickaxe nor a shovel.
If the chainsaw would make sense, I would have suggested to put it on that.
Hoe doesn't make sense either, 
Mowing tool doesn't make sense either.

So right now IC2Classic doesn't have a tool that does it that makes also sense to use it for. Unless you would say "minecrafts axe" makes sense to make path blocks...


I am always open to suggestions. But please consider, I was hounded by people about this topic... And neither had a solution.

**Comment by Maoman1** [comment]
I understand the points you're making, agree with them even, but I firmly believe the function needs to exist on _one_ of these tools, and since it doesn't really make logical sense to put it on any of them in particular, then it makes the most sense to put it on the one that emulates the shovel since the functionality originates there. 

"In my opinion it is ridiculous to be required to continue using shovels for one simple task despite having an advanced technological marvel of a borderline magical super drill in my hands."

Nothing you said addresses this, and it is the point I feel most strongly about. In truth I feel strongly enough about it that I do not believe any further argument should have even been necessary--this line _alone_ should be reason enough to give the drill the ability to make paths, realism be damned.

**Comment by CrossVas** [comment]
[GraviSuit](https://www.curseforge.com/minecraft/mc-mods/gravisuit-classic) is out for 1.19.2 and it has GraviTool - an advanced multitool (it has hoe, too)

**Comment by Trinsdar** [comment]
That tool doesn't do dirt paths though, and honestly not sure i could make that fit on it either, as the only mode even close to a shovel is the hoe, but that doesn't make sense there either.

**Comment by Maoman1** [comment]
So you're telling me that despite the drill's entire purpose being to remove the need to carry both pickaxe and shovel, I am required to continue carrying around a shovel for the mere privilege of using a dirt path, and I am required to do so because you refuse to accept the nearly insignificant ding against the mod's semi-realism? Gee, thanks. Next time instead of being polite and pretending to listen to me, just let me know in advance when I'm talking to a wall.

**Comment by Speiger** [comment]
Kinda reminds me of this.
https://www.youtube.com/watch?v=AsLILgB60sU

Anyways, I bet you were the first person when you always accedently pathed your grass instead of placing down torches from your offhand. Or that your drill wouldn't make path tiles when your offhand wasn't free...

Anyhow topic over.
