### ISSUE TITLE
Cannot pick up a generator with an electric wrench in lossless mode.

### ISSUE THREAD

**Issue by Maoman1** [TinyModularThings/IC2Classic#486]
Right clicking a generator with a standard electric wrench in lossless mode only opens the GUI, you must turn lossless mode off to pick up the generator.

**Comment by Speiger** [comment]
Dunno if you have one probe installed or not. But i would highly suggest you do it.
Because the wiki explains the wrench mechanics.

One probe tells you if you need the wrench to keep the block. (Wiki explains that how it tells you)

Basically generator, LV Batbox/Transformer, Iron furnace and stone machines do not need a wrench to be picked up.
They are lowest tech possible.

This was a thing since Any IC2 version.

**Comment by Maoman1** [comment]
I do have TOP installed, and it tells me an MFSU is safe to break with an ordinary pickaxe, which it clearly is not. 

In any case that does not resolve the original issue, because if you don't need a wrench to pick them up, then the wrench should not pick it up in _either_ mode. Whatever the behavior, it should be the same from lossless to normal--either it can pick them up in both, or it cannot pick them up in both.

**Comment by Speiger** [comment]
> I do have TOP installed, and it tells me an MFSU is safe to break with an ordinary pickaxe, which it clearly is not. It cannot be trusted.

This is explained in the wiki. "If a wrench symbol is present that means you need a wrench, if a wrench symbol isn't present that means you can mine it with the pickaxe"

**Comment by Speiger** [comment]
> In any case that does not resolve the original issue, because if you don't need a wrench to pick them up, then the wrench should not pick it up in either mode. Whatever the behavior, it should be the same in both lossless and normal mode--either it can pick them up in both, or it cannot pick them up in both.

Yeah the wrench should work with it... Ill look into it.

**Comment by Maoman1** [comment]
What wrench symbol? I see a pickaxe symbol and nothing else. The pickaxe gets a bright green checkmark with the drill, and stays a red X with the e.wrench.

https://imgur.com/a/SVfkRYo

**Comment by Speiger** [comment]
> I do have TOP installed, and it tells me an MFSU is safe to break with an ordinary pickaxe, which it clearly is not. It cannot be trusted.

That is a clear lie... Prooven by your posted Image here.
![image](https://imgur.com/R2HqfU4.png)

Especially since the wiki has "Screenshots" of how TOP looks like.
![image](https://user-images.githubusercontent.com/2556269/198888445-68e51226-8e30-4ab7-83c1-f47d57f3e482.png)


Anyhow, thank you for reporting the bug that the "Wrench overlay" seems to not highlight the colors it is supposed to.
Either blue/red.

What mods are you actively using?

**Comment by Maoman1** [comment]
>That is a clear lie... Prooven by your posted Image here.
Oh... I'm sorry, I mixed up WAILA and TOP (well technically I have Jade, but it's a fork of WAILA)
Modlist https://i.imgur.com/bh5q27G.png

**Comment by Speiger** [comment]
> Oh... I'm sorry, I mixed up WAILA and TOP (well technically I have Jade, but it's a fork of WAILA)

I know others exist, but for now since i actually helped the TOP dev improve his mod, ic2c only has special compat with TOP.
People can access all the data that TOP uses too if they want to have addons that support other WAILA/TOP like mods, but for now its only TOP.

Also why only top has special support: Because it has server side rendering and I don't need to deal with manually syncing data to make it look good. This is a lot easier for the developer.

> https://i.imgur.com/bh5q27G.png

Thank you I will look into that bug you found.
