### ISSUE TITLE
The industrial belt should NOT recharge the electric jetpack

### ISSUE THREAD

**Issue by Maoman1** [TinyModularThings/IC2Classic#489]
Well either that, or the electric jetpack should recharge my tools like a batpack (or higher tier), but I understand the reasoning for not doing so. But if the jetpack cannot recharge my tools, then the belt absolutely should not waste its power on the jetpack and instead _only_ recharge my tools. 

Being able to wear a recharging belt alongside the jetpack is a brilliant alternative to needing to switch back and forth between batpack and jetpack, but if the belt recharges the jetpack then it renders that whole concept useless. This is especially true with a compacted electric jetpack which burns through the industrial belt's measly 30k EU in no time at all.

**Comment by Speiger** [comment]
Simple answer: No.
Long answer:
There is 3 possible ways i can control it:
- Item can receive charge from armor/curio pieces
- Item can emit charge from the armor/curio slots
- Or disabled.

I can not set it to specific items only sending to specific items.
Its a global system.

And i am not changing that. Especially since you don't want your jetpack to run  out while you are mining glowstone over a lava pool.
You would rather your drill run out and your jetpack keeping its own charge so you won't fall out of the sky.

**Comment by Maoman1** [comment]
>I can not set it to specific items only sending to specific items.
Its a global system.

The simple solution then would be to disable the jetpack from receiving from other armor pieces. Yes that would stop the solar helmet, but the helmet is still extremely useful for all your other tools and nano armor. In comparison, the belt has absolutely no meaningful use right now. It is inferior to even the batpack, nevermind the lappack we all upgrade to at first opportunity, so it's only sensible use is when you want to be able to recharge items without wearing a bat/lappack... and the most significant time you need to do that is when wearing a jetpack. 

I mean really, when would you ever use the belt other than with a jetpack? It's not like chestpiece armor has an enchantment you cannot get from other armor pieces, and wearing a chestpiece + belt is only marginally more armor than wearing leggings + pack instead of a chestpiece. 

>Especially since you don't want your jetpack to run out of charge while you are mining glowstone over a lava pool.
You would rather your drill run out and your jetpack keeping its own charge so you won't fall out of the sky.

I mean yeah that sounds all well and good, but in actual practice it winds up being completely backward from that. 

Think about it: The jetpack drains the belt incredibly quickly and _then_ relies on its own internal power supply, which lasts significantly longer, so if your jetpack runs out, your belt was already looooong dead. And I don't know about you, but when *I'm* mining with my condensed jetpack, my drill goes dead before I've even made it 20% through my condensed jetpack's charge. 

Then I have to stop, swap to my lappack, mine one random block really slowly with a dead drill to recharge it, then swap back to my jetpack before continuing. It's tedious and annoying and we have to do it multiple times per mining trip... and there's a simple solution staring us in the face: If the belt's charge _didn't_ get obliterated by the jetpack in the first 5 minutes of your mining run, then the drill now has a total of 40k EU to pull from instead of its mere 10k internal battery. 

Seriously, what is the point of the belt, if not this? Please, explain.

**Comment by Speiger** [comment]
Ok,
This is now 2 for 2 for bad ideas that you try to justify.

I am not even going to argue about this.
The long answer was just to give you reasons why it won't happen, not to justify it.

The simple answer applies here: No.

If you have bugreports that is fine, please provide sufficient info so i can fix those,
but i am no longer arguing about suggestions like these that scream "downsides" like no tomorrow.

Ignoring the fact if you looked around in ic2c that what you ask is already possible.
(Jetpack not taking power and also sharing power, though the latter one is only optional if the first one is set)
And I am not going to explain that either since everything that make that possible are explained in the wiki, so figure it out yourself.

Anyways thanks for the suggestion.
But no thank you.
