### ISSUE TITLE
[1.19.2] Infinite lava bug / You can't pick up lava from lava logged cables

### ISSUE THREAD

**Issue by Kanzaji** [TinyModularThings/IC2Classic#492]
## Description
After you place lava on the cable, you can't pick it up without breaking a cable. Trying to pick it up with fluid cell causes to dupe lava.

## How to reproduce
1. Place any cable in the world
2. Place lava in the same place
3. Try to pick it up with a bucket (fluid cell for infinite lava)

## Screenshots / videos
https://youtu.be/bu9ELUFr12Y (Quality will be bad for like 15 minutes at the time this report is made, Youtube is doing some stuff with the video)

## Other mods:
I use Enigmatica 9 Develop version of 1.0.3 (Between 1.0.2 and not released yet 1.0.3) with IC2C added
https://github.com/EnigmaticaModpacks/Enigmatica9

**Comment by Speiger** [comment]
Really lucky find. 
I assume a bucket doesn't dupe?

Is that a priority for you? Or do you think the [Milestone](https://github.com/TinyModularThings/IC2Classic/milestone/6) is within reason?

**Comment by Kanzaji** [comment]
> I assume a bucket doesn't dupe?

Yup, bucket is "fine", it doesn't work and doesn't dupe. Cell doesn't work but dupes the lava.

> Is that a priority for you? Or do you think the [Milestone](https://github.com/TinyModularThings/IC2Classic/milestone/6) is within reason?

The biggest problem that comes with this issue is Thermal Generator, as you can surround it with lava for more Power. But it isn't game-breaking bug, so it is up to you if you want to fix it on the earlier date ^^"

**Comment by Speiger** [comment]
> Yup, bucket is "fine", it doesn't work and doesn't dupe. Cell doesn't work but dupes the lava.

Ok that's good to know.

> The biggest problem that comes with this issue is Thermal Generator, as you can surround it with lava for more Power. But it isn't game-breaking bug, so it is up to you if you want to fix it on the earlier date ^^"

Yeah this is a bug within my code.
And while I see that this is an issue, I don't want to spam releases for each fix, I rather do bulk fixes.
But I can also see where a pack dev could say this is "really critical" for me. That's why I asked.

Also you could just go in the nether and do the same with its giant lava reserves, or dry up a lava lake underground.
This is just more "convenient" and if this drives people away from doing solar spam because they don't know anything else. I don't mind having this "dupe" bug there for a couple weeks.

So thank you for reporting @Kanzaji 
If you find more let me know!

**Comment by CrossVas** [comment]
Also Electric pump is taking it as a source block and gives you infinite lava (very convenient actually, using it rn :D)
Demo: https://youtu.be/4qtO8CqXbGk

**Comment by Speiger** [comment]
@CrossVas just remember that next patch will remove said problem.

**Comment by CrossVas** [comment]
Sure thing, yeah. No problem.

**Comment by Speiger** [comment]
This is fixed, I just forgot to put it into the changelog.
