### ISSUE TITLE
[1.19.2] Create's JEI handler shows hidden recipes.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [TinyModularThings/IC2Classic#509]
![2022-11-06_13-32-41_e0d182c9-0d64-453c-92f3-d7e8b855f621](https://user-images.githubusercontent.com/5104603/200165986-ba623b99-43e1-4182-a230-6ceb303525ad.png)
![2022-11-06_13-32-47_0bfd20b4-9a58-4e3f-9172-a1bb5b2fc6d3](https://user-images.githubusercontent.com/5104603/200165987-0a385a78-f682-440d-a27e-3293cbc7ed9b.png)

IC2C 1.19.2-2.0.1, Create 1.19.2-0.5.0.f

**Comment by Speiger** [comment]
The UU Matter to iridium recipe is shown by default. This is just to aid progression since Iridium is now really important.
So thats not a bug.

About the Create thing.
Please open a issue at their issue tracker since I can't control Creates JEI handler.

if they are willing to fix it, i will provide them with as much info as they need.

**Comment by YuRaNnNzZZ** [comment]
> The UU Matter to iridium recipe is shown by default. This is just to aid progression since Iridium is now really important.
So thats not a bug.

I know, that was always the case in IC2. I've put the crafting tab screenshot to show that there are no IC2C recipes displayed other than Iridium one.

**Comment by Speiger** [comment]
@YuRaNnNzZZ just reference this issue in your Create issue and I will offer my help.
