### ISSUE TITLE
High EU output with parallel Batboxes does not damage copper cables

### ISSUE THREAD

**Issue by NavedNoor** [TinyModularThings/IC2Classic#515]
It’s possible to power for example 4 induction furnaces using 3 batboxes by connecting them parallel with a copper cable. The problem is that the copper cable normally has a EU Limit of 32 EU. 4 induction furnaces use 64 EU and they were running without a problem and without a single cable burning. I was even able to read the high EU flow of 64 through the copper cable with an EU-Reader. Normally the cable should burn. I haven’t tried this with higher tier machinery and cables but I suppose it’s also possible.

**Comment by Speiger** [comment]
Read the Tutorials.
It say "32EU per packet" each emitter counts as 1 Packet.
That means EU Cables can have infinite power flowing through it if you want to if you can put it into enough packets.

(Transformers for example convert 1x 128EU into 4x 32EU. Meaning if you use transformers from an MFE you already overload cables but since they are below the packet limit they are fine)
