### ISSUE TITLE
[1.12.2] Upgrades not working Industrial Craft Classic

### ISSUE THREAD

**Issue by Blaze1499** [TinyModularThings/IC2Classic#517]
Basic details

    Are you using a legitimate Minecraft account?: yes
    Are you using Java 8, 64-bit?: yes
    Did you add any additional mods: yes (Tekkit 2 modpack)
    Crash/latest log link (if applicable): not applicable

Describe the issue

Tried putting a single overclocker upgrade into various tier 1 ICC machines, (Macerator, Compressor, Extractor, Electric furnace), and despite having plenty of power in my MFE, saw no speed increase on any of these machines. According to the wiki, the macerator should have its processing time reduced from 20 to 14 sec/item, but i saw no such increase. I also tried a Muffler upgrade in a rotary macerator and heard no reduction in noise

**Comment by Speiger** [comment]
Thank you for the report. We found these exact issues during the 1.19.2 port, but only addressed them there.
> Overclockers Not working

The overclockers only work if they exceed the integer threshold. So 0.99 gets rounded down to 0.

> Mufflers not working

Yep this is the same issue.

A temp solution is just throw in more. I know for a fact that 2-3 work fine, its just the first that doesn't do anything.
IC2C 1.12 is right now on a "maintance halt" until the next year. Unless there is a critical bug found that breaks the entire mod.

Thank you for the report, I will address it when I am doing the next patch.
I am keeping this open since otherwise I am forgetting it.

**Comment by Speiger** [comment]
Fixed
