### ISSUE TITLE
IC2 vs Cauldron

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#56]
Electrolyzer not charge cells in the server kernel Cauldron. On Vanilla kernel server works fine.

Cauldron Server Version: 1.7.10-10.13.3.1403
Forge Server Version: 1.7.10-10.13.3.1403

**Comment by Speiger** [comment]
Well thats interesting...
I am thinking of that something is not get loaded right or they handle Trashing data differend which could be a thing that he looses all his RecipeData...
Now i can do nothing because i am not at coding and i planned the next IC2 Classic Coding session tomorrow...
But i will add some Test logs so that you can see what happens...

**Comment by Dr0n1k** [comment]
Thank you very much.

**Comment by Speiger** [comment]
@Dr0n1k please send me a message at the IC2 Forums if you have a account there...

**Comment by Dr0n1k** [comment]
@Speiger I send message for you

**Comment by Speiger** [comment]
@Dr0n1k thanks already answered and also prepairing. You will understand when you readed the message

**Comment by Speiger** [comment]
Fixed. Simply was a ID Missmatch because cauldren seem to load stuff differendly. Could be an IC2 or Cauldren bug not sure but it is no longer there :)
