### ISSUE TITLE
[1.19.2] Aluminium is not properly tagged.

### ISSUE THREAD

**Issue by Zeitheron** [TinyModularThings/IC2Classic#563]
Hello! Expanded Equivalence dev here.
When I was doing IC2 Classic compat, I have noticed that aluminium ingot was not in the `forge:ingots/aluminum` tag.
Please map it into that tag, it is in use by other mods, and letting your aluminium be cross-compatible with aluminum is a good idea.

**Comment by Speiger** [comment]
@Zeitheron we use the "forge:ingots/aluminium" tag for everything since that wording is the "global" standard.
aluminum is US/Canada Exclusive way of writing it.

**Comment by Zeitheron** [comment]
Mods do use Aluminum, so I'd suggest adding to both.

**Comment by Speiger** [comment]
That is fine. IC2C Aluminium is also kinda balanced in a way where its early game really important since its a gateway ingredient.
but after that getting that unlocked getting 10 million ingots within a IRL week isn't really unrealistic to begin with.

So might be better if these things stay split.

**Comment by Speiger** [comment]
Anyways, if you want to make IC2C Aluminium compatible with the forge tag, then you are free to do it.
But honestly, I doubt I will address this anytime soon.

Don't see this as a ill will or me saying everyone else is wrong.
Its more about, i choose to do it way because i think its more reasonable this way.
