### ISSUE TITLE
Issue with Ic2 classic and galacticraft teleportation

### ISSUE THREAD

**Issue by JoeGiachetti** [TinyModularThings/IC2Classic#581]
The portable teleporter does not work when the target is a galacticraft space station and the player in in another dimension. I have the space station pre loaded and have tried this on both single player and multiplayer. Both result in crashing. I am specifically using these mods as a part of the tekkit 2 pack.

**Comment by Speiger** [comment]
Please provide a crash log.

Also I have seen a letsplayer use the teleporter with galacticcraft and it was fine.

**Comment by JoeGiachetti** [comment]
This issue only happens when I teleport from another dimension to my space station using the portable teleporter. I am able to use the portable teleporter to reach any other dimension including the other planets. After using it, my game does not update but the server doesn't crash until I leave the game. The server is hosted so I will get back to you on the crash log.

**Comment by Speiger** [comment]
Yeah but this can be galactic crafts issue, and not ic2cs.
Since planets work fine and only space stations are freaky. Meaning they require special stuff i can't do.

**Comment by Speiger** [comment]
@JoeGiachetti yeah this is galactic crafts problem not mine.
When i store the "Location" i store the current dimension Id.
If it doesn't exist because galacticraft doesn't store them properly that's not my bug.

If the GC team needs my assistant they can ping me and i provide my help if i can.
But this isn't a ic2c issue.
