### ISSUE TITLE
Tin Cables

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#6]
They used to have a transmit limit of 8EU/t before melting, but yours has a limit of 5.

**Comment by Speiger** [comment]
Nope its 5 EU max. Checkt in the IC2 1.2.5 SourceCode...

**Comment by Chocohead** [comment]
I thought it changed in 1.4.7? The cable values doubled for each tier.

**Comment by Speiger** [comment]
Nope in 1.4.7 it was even 3 EU per tick... So^^" I should low that. But the idea is that you can use windmills with the tin cables too. Because they can max output 4 eu then everything is fine with 5 eu limit.
I did check the source before i answered.

**Comment by Chocohead** [comment]
I thought that windmills could output more than 5EU/t if they're too high, and have a chance to explode if they do.

**Comment by Speiger** [comment]
True their limit is at 4 eu when it go higher then they explode.
Since the wind logic (my or old one) never reach the point where it can explode... (i checked that with running it 64000times faster i and logging the lowest and the highest number)
So 4EU Transfering is ok. (When it reach 5 eu the tin cable melts)

**Comment by Speiger** [comment]
Closed. Will not be added.
