### ISSUE TITLE
§7net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: direwolf20:textures/ui/button/DWL_auxilium.png

### ISSUE THREAD

**Issue by AshleighTheCutie** [TinyModularThings/IC2Classic#601]
Error code is in the title. I added this to DW20 1.19, and it's doing that now. It's running fine on the dedicated server.

[latest.log](https://github.com/TinyModularThings/IC2Classic/files/10531019/latest.log)

**Comment by Speiger** [comment]
The Direwolf mod that adds said texture is breaking the "resourcepack format" this isn't a ic2c issue because it just scans the resource packs which is allowed, the file itself causes the crash.

Now IC2C bug.
Report it to the pack dev to lowercase the file.
You can fix it yourself by searching for the file and lowercasing it yourself, that will fix it.

**Comment by AshleighTheCutie** [comment]
> 

Where did you find that's it's disallowed to have uppercase characters?

**Comment by Speiger** [comment]
@AshleighTheCutie Non [a-z0-9/._-] is a regex indicator.
a-z => any letter between a to z, but all lower cased.
0-9 => any number
/ => literal slash
. => literal dot
_ => literal underline
- => literal minus.

Also if it crashes at a texture that has a uppercase name its a good indicator.
Also this bug was reported multiple times and was fixed the moment people lowercased the name of the file.

**Comment by Ushupiuck** [comment]
@AshleighTheCutie you can fix this issue manually tho. If you navigate to the folder where the pictures are loaded (it's in your .minecraft folder) and change the names to be lowercase, this goes away
