### ISSUE TITLE
nuclear control + big reactor crash on startup

### ISSUE THREAD

**Issue by evilpdor** [TinyModularThings/IC2Classic#62]
latest version of ic2 (classic 1.0.9.10) + latest version of nuclear control (2.2.5a-GoingForTheKill) work well, but if you add BigReactors 0.4.3A nuclear control crash minecraft on startup.

nb: with latest ic2 experimental, nuclear control + big reactor work.

crash log: 
http://pastebin.com/kpPnbVNK (with nuclear control 2.2.1a-Yolo)
http://pastebin.com/8MLaU7zK (with nuclear control 2.2.5a-GoingForTheKill)

**Comment by Speiger** [comment]
Not a Classic bug at all... Its a bug with your forge version... Nuclear Control is update to an UnStable version (when i did bring out classic 1.0.9.10 it was an unstable one), and there are simply minor changes between them...
Wait until the Next Classic version that will be up to date with forge.
I can at the moment not update quickly reason for that is simply because i am making big changes to classic + extra additions and at the moment nothing in there is stable enough for a release...
(Simply try downgrade NuclearControl and look for the required forge versions...)

**Comment by evilpdor** [comment]
i'm use forge stable 10.13.2.1291 and is pretty old.

**Comment by Speiger** [comment]
As i said the Forge version was not compatible with Nuclear Control...
^^" With the next update i upgrade to the new Recomended forge version and then there will be no problem... Also little Classic support from Nuclear Control for Steam Reactors (will be with the next update) will be there if xBony let me implement it to NuclearControl

**Comment by evilpdor** [comment]
I fix the source of nuclear control to make it compatible with this 3 mod, the code is messy but it works. If anybody cares I can give the changes that I made.

**Comment by Speiger** [comment]
Closed. Just wait on NuclearControl and IC2 Classic update
