### ISSUE TITLE
[1.19.2] Hazmat Suit 

### ISSUE THREAD

**Issue by burymesoftly** [TinyModularThings/IC2Classic#620]
For some reason it protects like a real armor
![2023-02-12_14 39 37](https://user-images.githubusercontent.com/125179011/218299306-c2821449-df8c-424c-a153-9b96e0209029.png)
![2023-02-12_14 40 04](https://user-images.githubusercontent.com/125179011/218299307-7ce1a330-ef6a-4f0b-92a5-ba2eaa271e2e.png)
![2023-02-12_14 40 01](https://user-images.githubusercontent.com/125179011/218299308-f6cd9441-0a6e-4914-9248-79aa114bdfd0.png)
![2023-02-12_14 40 08](https://user-images.githubusercontent.com/125179011/218299309-238d0eb3-a93d-4717-935e-7d7019ce5fe7.png)

**Comment by Speiger** [comment]
That is intentional.
Since if you were in a rubber suite it also protects you from a bit of damage too.
But it breaks easily.

**Comment by burymesoftly** [comment]
Full set protects you not from a bit but almost all damage, yes, it breaks fast, but is it really intentional that rubber makes you invincible for a while?

**Comment by Speiger** [comment]
Fun fact: Minecrafts armor calculation will only absorb ~80% of the damage iirc, anything extra will be still let through.
Though that isn't as visible since the hearts are a Integer, while the actual health is a float.
Meaning you still can die even in diamond armor with perfect enchantments if you don't have regen and a person punches you long enough.

But yes this is intended.
