### ISSUE TITLE
In the wiki, ic2.wiki.translated is untranslated

### ISSUE THREAD

**Issue by aaronhowser1** [TinyModularThings/IC2Classic#634]
![image](https://user-images.githubusercontent.com/15698722/220490352-9ea8c625-5df2-4ffe-a7c0-53c3a68cdf26.png)

Ironic

IC2Classic-1.19.2-2.0.3

**Comment by Speiger** [comment]
@aaronhowser1 can you please also show if that happens only with vanilla+forge+ic2c?
Because i actually translated the translatedBy entry in english but left it empty so it wouldn't have anything so it wouldn't show up in the first place.

So the question is is this a mod that breaks a "Dynamic page"?

**Comment by aaronhowser1** [comment]
Yes, this happens with just Forge and IC2C
![image](https://user-images.githubusercontent.com/15698722/220899103-9a98be0b-3eeb-49e3-96bf-722eb59d8bca.png)

latest.log https://gist.github.com/5270d379d2ab933bfcafc2d875bb39a5
debug.log https://gist.github.com/9eb4d517594ca18d1dd4f60c3820d076

**Comment by Speiger** [comment]
ty i will fix that
