### ISSUE TITLE
[1.19.2] Visualization should not be visible through opaque objects

### ISSUE THREAD

**Issue by KennysDaywalker** [TinyModularThings/IC2Classic#636]
It then looks as if it moves with the player.

![2023-02-23_16 30 29](https://user-images.githubusercontent.com/40204217/221013041-b3e2479e-a47f-4102-8768-91838b802f31.png)
![2023-02-23_16 37 42](https://user-images.githubusercontent.com/40204217/221013134-5bc58805-0e26-4f9b-8d9c-cf25c0b697c4.png)
![2023-02-23_16 37 49](https://user-images.githubusercontent.com/40204217/221013145-bfffa043-e277-48a5-8c8f-58bf7733366f.png)

**Comment by Speiger** [comment]
Ok I had the choice of doing 2 things. Bot resulting into 2 problems:
- 1: Enable the Depth buffer. Fixing the exact issue what you are having. (The box isn't moving its just a optical illusion because no depth) But that would mean you don't actually know how the big the box is without digging all blocks around it. (Underground that is painful)
- 2: Disable the depth buffer. This causes the issue you are having. But it allows to see how large the box is. Yes there is optical illusions included but the general idea for things is provided. And there is no surprises that you couldn't see.

I went with Option 2 and that will not be changed.
