### ISSUE TITLE
[Question|Request] Supported Version

### ISSUE THREAD

**Issue by accessdenied0** [TinyModularThings/IC2Classic#641]
Normally I really do not do that... but since most of the current mods and supported editing mods are on 1.18.2...

I wanted to ask how big the chances are for a 1.18.2 port?

I really would love IC2Classic for this version (for a (private) modpack of mine)...

I apologize for this annoying request/question since I am sure you get ton of... but since I not have found a similar question I couldn't contain myself to ask. 

In any case great work with this mod!

**Comment by Speiger** [comment]
No worry. Its fine to ask and I get more requests for 1.19.3 then other versions.

But IC2C is not going to be ported to 1.18.2 or any version between 1.12.2 and 1.19.2     
Basically I port to the versions i play and I never intent to play on that specific version.

Again no worry about the request since you are the first to ask.     
And thank you.    

I wish you a great day/night.
