### ISSUE TITLE
Quantum armor and nano armor should not break if discharged!

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#662]
Quantum armor and nano armor should not break if discharged!

**Comment by MrJorman** [comment]
Please disable this function in the configuration.

**Comment by Meduris** [comment]
wait, how exactly did you discharge them? Apart from a random chance for this to happen when being attacked with a nano saber, I don't think this should be happening

**Comment by MrJorman** [comment]
My nano armor and quantum armor is completely broken by the nano saber

**Comment by MrJorman** [comment]
Such mechanics were in IC2 even on minecraft versions in 1.2.5

**Comment by MrJorman** [comment]
But then they made sure that the nano and quantum armor did not break from the nano saber

**Comment by Meduris** [comment]
I know for sure, that IC2 Classic had it this way all the time since at least minecraft 1.10 and considering it was a thing that long ago, it most likely never got removed in Classic.

This was to my knowledge never a bug but rather intentional, though I can see your point in at least wanting a config to turn that off (especially now with the armor modules), but ultimately thats for Speiger to decide

**Comment by MrJorman** [comment]
I think that it is necessary to make it so that the armor destruction function can be turned off, since in PVP between players it will not be possible to get armor.

**Comment by Speiger** [comment]
@Meduris @MrJorman this "Feature" of the nano saber being able to break the Nano/Quantum armor is actually intended and will not be changed.
And it is not a bug.

**Comment by MrJorman** [comment]
> @Meduris @MrJorman this "Feature" of the nano saber being able to break the Nano/Quantum armor is actually intended and will not be changed. And it is not a bug.

So it was before in the old versions of IC2, then this function was removed.
