### ISSUE TITLE
Where can I remove crafts? Can't find recipes in data-recipes folder

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#667]
Where can I remove crafts? Can't find recipes in data-recipes folder

**Comment by Speiger** [comment]
https://github.com/TinyModularThings/IC2Classic/wiki/1.19.x-ResourcePacks

We do a lot of custom shit because the mod is gigantic and writing over 1000 json files to make the same thing happen slower isn't really an option.
And vanillas auto generators use still 5x more code then what we did.
No worry json files are supported and ic2c has a serializer to make the entire system datapack based but it was only added in the few patches after the mod was done.

Just use the wiki entry that i finished like 5 days ago that will show you how everything works.

**Comment by MrJorman** [comment]
I was able to change the recipes, but where do I put datapack.zip in order for the recipes to apply?

**Comment by MrJorman** [comment]
Understood.

**Comment by MrJorman** [comment]
I can't figure out how to remove the recipe from the mechanism, I created remove.json file and added to it 

{
"remove": ["ic2:potato_slices", "ic2:sliced_potatoes"]
}

no working

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/224300247-d5251709-b542-4d1c-98dc-a4568b42c1ba.png)
wtf

**Comment by MrJorman** [comment]
How to remove this craft, help?
