### ISSUE TITLE
[1.19.2] Quantum armour does not protect player from warden sonic damage

### ISSUE THREAD

**Issue by himekifee** [TinyModularThings/IC2Classic#669]
It's said to be "sonic", so I don't think it should be non-intuitively counted as "magic" damage. Also, quantum armour has been considered one of the most powerful armours in the MC mod community. Lastly, it's a pain in the ass to get back the inventory containing hundreds of hours wasted to be crafted quantum armours in 5 mins of item disappearing time. Please, consider about that.

**Comment by MrJorman** [comment]
+ agree. need fix.

**Comment by Speiger** [comment]
First of all @MrJorman this is not a bug or something that needs to be fixed.
Because this assumes it is "broken" in some form.
Which this issue isn't. I just haven't decided on what I want to do with it.

@himekifee i have come to a choice on this topic.
The Quantum Armor can block the Sonic Boom Attack from the warden now.
But only under 1 condition. You need a full set of Modular Armor (Nano/Quantum) equipped otherwise it will be not protected against.
Reasoning is: If the sound slips through for any reason you get hit by it 100%
