### ISSUE TITLE
heat_storages do not stack in the inventory, thus heavily polluting it.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#685]
heat_storages do not stack in the inventory, thus heavily polluting it.

**Comment by CrossVas** [comment]
Every Heat Storage component has its own durability, thus it should be treated as a tool. Does **any tool** stack in inventory? No. This is an intended behavior since **the beginning of time**. Also see image.
** Minecraft 1.4.7 with give command displaying in chat.
![image](https://user-images.githubusercontent.com/25727222/224584443-986bf94d-2e8e-4b9f-8a59-a13cb3c99645.png)

~~P.S. Also could you please use discord for such questions? They do _pollute_ github issue tracker.~~

**Comment by MrJorman** [comment]
ok
