### ISSUE TITLE
[Idea] New crafting table for UU-Matter, energy needed to assemble (deactivatable in config)

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#69]
UU-Matter from old versions of IC2 is too OP. You obtain it as item and then you are able to craft its results everywhere you are. My idea is a new crafting table that needs energy to works, a bit of the same way the automatic crafting table from BuildCraft does, in order to craft recipes from UU-Matter. Of course, you can disable that behavior in the config.

**Comment by Speiger** [comment]
First UUMatter is only providing base Resources of IC2. With Other Modintigration, it is not OP because it does not provide that much more things to the world. (It depends on your modpack simply),
Also ScrapBoxes are way more OP then UU, Because you can gain way more resources out of it then in UU. That includes Emeralds and Food and all the other things you need. You gain even EU out of it^^.

To the Suggestion. I did think of that idea to. But instead of Using EU for Every Item, i did think that the base Resources cost only UUMatter, but this table would provide also Items that can be crafted out of these things that it normally provide via crafting it in craftingtable. It search in the recipes and allow up to 3 items that it can not generate by its own (these you would need to provide yourself), and it would use 500 EU per needed Crafting Step. It would be instant. Not delayed... (Maybe)

**Comment by Carbon-Ghost** [comment]
Too complex Speiger, sounds like AE2 combined with Crafting Table III ;P

I like the original idea though :)

**Comment by Speiger** [comment]
Codewise it would be close to the Exp version of UUMatter detection (what can be scanned) but for users it would be not complex at all...

**Comment by Carbon-Ghost** [comment]
Here is my final opinion : 

-I am ok with a crafting table with UU-matter for crafting more advanced stuff, or just as a replacement, you idea also seems ok but if possible can you make it configurable please ?

**Comment by Speiger** [comment]
Config is not a problem.

**Comment by Speiger** [comment]
closed for now... This update will not gonna have this...
