### ISSUE TITLE
The electric wrench does not waste energy when used and does not waste energy in "lossless mode" works crookedly

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#698]
The electric wrench does not waste energy when used and does not waste energy in "lossless mode" works crookedly

video: https://youtu.be/CCsmAivqNME

**Comment by Speiger** [comment]
First of all if you make a video showing text. Show it in English, because i can't read russian.
Second:
Lossless mode only drains uses/the massive power if the machine would have been LOST 
otherwise it won't drain more then it needs to.

This is intended behavior...

Why? Because while lossless mode was wasting a lot of power for infinite uses, it was also Annoying AF to use.

**Comment by MrJorman** [comment]
so in the video, with the usual twisting, the energy will not be used up

**Comment by CrossVas** [comment]
Each wrench has a drop chance. When you are not lucky and lose your machine, your wrench, if it has Lossless Mode enabled, will override this chance, making it 100%, but will use 10k energy. This way, you don't lose your machine.
On the other hand, if you are lucky, you will get your machine back and will save energy.

У каждого ключа есть шанс выпадения. Когда вам не повезёт и вы потеряете свою машину, ваш гаечный ключ, если в нем включен режим без потерь, переопределит этот шанс выпадения, сделав его 100%, используя при этом 10к энергии. Таким образом, вы не потеряете свою машину.
С другой стороны, если вам повезет, вы вернете свою машину и сэкономите энергию.
