### ISSUE TITLE
There are no descriptions on the wiki and in the book

### ISSUE THREAD

**Issue by RainbowExile** [TinyModularThings/IC2Classic#700]
There is no description of the bulk crafter mechanism either in the book or on the wiki, and there is no article about pipes on the wiki, and there is also no description of how pipes work on the wiki, insufficiently detailed description in the book and no examples of how to use them.

**Comment by Speiger** [comment]
@RainbowExile there is a "S" button in every gui.
That button means: "What goes into what slot"
Try filling in the items and see what happens.
And maybe look where they are used otherwise.
Try/error a bit.

**Comment by RainbowExile** [comment]
This would be acceptable if I played any magic mod. But industrial is a tech mod and I should have the tech doc. I'm already tired of going into the creative for every sneeze. For the last week, almost every object or mechanism has to be tested, sometimes for 20 minutes, sometimes for a couple of hours. In GTNH and even less stuffiness. Lack of information is never fun and makes it very difficult to bring many ideas to life, because each idea takes from a third to a half of the time to understand how this or that machine works.

**Comment by Speiger** [comment]
@RainbowExile so requiring specific items to be in specific slots, where i give you tools to figure that out instantly, is to complex for you and needs to be in highly detailed description how to use them?
Do i need to preeat your food too?

- You need Crafting Upgrades to init the craft (Because they do the crafting, so stacksize decides the crafting per cycle)
- Speed upgrade can be inserted to another slot that speed up the process. (Decides the delay between cycle)
- Memory Stick Provides recipes. Which you need a tool to insert recipes to. (Searching Memory Stick in the wiki will show you the Industrial Worktable, that may or may not allow for that.)

That is all the logic.
The most complex part is how to get recipes into the Memory Stick, which may or may not confuse people but the REST can be easily figured out by using the: "WHAT GOES IN WHAT SLOT BUTTON, that displays you exactly the item you want that you could even use JEI keys in"

Do you need more pre-eating from my mouth?

**Comment by Karo4a** [comment]
There is no information about Bulk Crafter in the wikipedia book, and it is also absolutely not clear that Upgrade: Craft is necessary for its work.
It is unclear what kind of Keep Mode/Per Item/Global - Provider pipes have, the other two modes (Paper and Book) do not have a graphical signature when hovering.
I only recently saw a category of tabs with Tutorials, just because in Search you can't find any of these items in Tutorials.

**Comment by RainbowExile** [comment]
Firstly, if you made a book with the name of a wiki, then you can’t just take it and poke it yourself. The wiki contains the characteristics of the mechanism: Voltage, how much energy it spends. with what speed it works, etc. M The information must be complete, and not fragments like a thermonuclear reactor generates lava, just drop something that melts. There should be recipes in JEI, how fast the rods are spent, how much and how long it generates. And such key information is not available almost everywhere. just some water instead of useful information.
And secondly, don't be an asshole.

**Comment by Speiger** [comment]
@RainbowExile 
First: 
If you want exact detail down to the exact formulars etc, then leave. Because I am not going to provide exact values.
Why? Because it is just not as accessible as approximation.
That's why i went that route.

Second:
There is only so much i can take in a day.
Reasonable requests are fine, but wanting me to effectively rewrite everything, because that is what you are asking, is unreasonable to the point where i say: fuck off.

There is a difference in design Philosophy.
What i want to give you is the tools you need to figure everything out, but i don't want to to dumb everything down or throw to much at you.
So thats why it is the way it is.

If you have a problem with that, that is not my problem.
If there is a actual issue that is a different topic. But this example is not an issue. At least from the point you are coming from.

**Comment by Speiger** [comment]
@Karo4a 
> It is unclear what kind of Keep Mode/Per Item/Global - Provider pipes have, the other two modes (Paper and Book) do not have a graphical signature when hovering.

How about you try it out what it does?
"keep mode" at least give you the info you need to figure it out.

**Comment by Karo4a** [comment]
@Speiger we don't suggest that you rewrite everything yourself, you can make it so that if people don't like some description of wikipedia, then they themselves would offer a better description. And after your approval, it will go into Wikipedia.

And another question, what is the problem with writing formulas? The answer that comes to my mind is that some part of the code was written before you.

How do you think we should find out how much water a steam reactor consumes? Stand under the threat of an explosion and count the amount of water? Spending your time on a thing that you need to know initially?

Ignorance of something can lead to an error, we ourselves create mechanisms in minecraft why can't we know everything about the structure of these mechanisms?

**Comment by Speiger** [comment]
> How do you think we should find out how much water a steam reactor consumes? Stand under the threat of an explosion and count the amount of water? Spending your time on a thing that you need to know initially?

How about you use a "Reactor planner" that makes a simulation and gives you the tools to figure that out?

> Ignorance of something can lead to an error, we ourselves create mechanisms in minecraft why can't we know everything about the structure of these mechanisms?

I don't say that "You can't know everything", it is just that i said: "I won't give you every exact detail for the reason of accessiblity".
If you want to have exact values you  can run tests and see how much it consumes.
These machines are not so insanely complicated that it takes much to figure this stuff out.

And there is multiple other ways to do such a thing.

> we don't suggest that you rewrite everything yourself

 You may not, but the other person did.

> you can make it so that if people don't like some description of wikipedia, then they themselves would offer a better description. And after your approval, it will go into Wikipedia. Many people may simply not know about this possibility - to rewrite part of wikipedia for the better

If you want a wiki with exact values, figure them out and create your wiki with it.
Nobody stops you making a fanwiki, i am just telling you that the base wiki ingame that is important to 99.999% of the people is the way it is so it is accessible.
Anyone wanting to know more or is interested to know more will test things to get exact values.

Fun fact there is a few youtubers who made contraptions trying to make the best they can and they came pretty close without asking the dev: PLEASE FORCE FEED ME THIS INFO.
Instead they went down the rabbit hole and figured that stuff out because it was fun to them.
And if i found something that they didn't know i would just offer that helpful info to them specifically.

But these are edge cases.

The ingame wiki is not for edgecases it is for 99.99999% of the people.
And that from what it looks like isn't you two.
