### ISSUE TITLE
Add Items Separation to Colossal Machines

### ISSUE THREAD

**Issue by Karo4a** [TinyModularThings/IC2Classic#702]
I got to the colossal machines and what was the surprise that I could not automatically divide items into the number of free slots in them?! I want to add this feature so that if I have 64 items and when I put them into a 2x2 colossal machine, then the items are divided into 2 by 32 in each slot and so on with large sizes. This function will accelerate the possible performance of the machine with small volumes of items. This is the last tier of machines, they SHOULD be able to do this.

![image](https://user-images.githubusercontent.com/90093987/225358096-e3e9e4ea-6395-4502-ad0b-890f182ba540.png)

**Comment by Daenara** [comment]
One problem I see with that is how would the machine know you want to divide the items. You could have thrown a stack in there and be done, then dividing would make sense. But you could also throw one stack in, get a stack of another item you want to put in and you can't because it already divided the first stack to fill all slots.

Most common use case for those machines is batch processing. You rarely only have one stack and I would assume most ppl fill those machines up automatically as well

**Comment by Speiger** [comment]
@Karo4a this is a endgame machine for bulk processing.
Yes splitting could work in a low amount processing, but why do you use such a high end machine for Bulk processing in the first place?
You don't process 1 stack with this kind of machine, you process 1000 stacks with this machine with various different resources.

Anyways @Daenara summed it up the best what i think of it.

**Comment by Karo4a** [comment]
Okay, I realized my mistake. Naturally, it is true that they are properly used to process a huge number of resources.

However, what prevents them from using them personally? That's right, nothing. And a competent distribution of items is just the same necessary, because we do not want to wait, simply because the mechanism does not use its full potential in speed?

It is unprofitable for me to use a mechanism that needs to be warmed up during transfer (MV), and mechanisms at a lower level (LV) are too slow and less energy efficient with accelerators.

I want to use this mechanism, because its speed is great, and processing 2 - 8 stacks at a time (depends on the size of the colossal mechanism) is not always practical due to the present resource savings.
I just want to use the maximum speed that this mechanism gives, because time is money.

For some reason, you consider my proposal as a global introduction, why do you dismiss this idea, because its implementation is simple? Just add one button that enables this feature.

**Comment by Karo4a** [comment]
I wouldn't be surprised if you dismiss my idea again.

**Comment by Speiger** [comment]
Mainly because processing 1 stack in a Advanced machine takes 38,4/19,2 seconds. (Induction smelter produces 2x speed)
And if you need a faster machine you would take a Uber LV machine which takes 3,2 seconds to process 64 items.
For 1EU per item (64 EU per stack)
And these machines are much more reasonable for a workshop to begin with.
While a Colossal Machine needs 19.2 seconds to process one stack in 1 slot. (2 slots => 9,6, 4 slots => 3,8, and 8 slots => 1,9 seconds)
And taking 30EU per tick per active slot. So instead of paying 64 EU you pay 9120EU for slightly faster but insignificant speed.

A colossal machine could be auto sorting between inputs and balance the outputs too but on the other hand it would be unnecessary IMO and takes optional lag to keep up with the processing not to stall it. (Because the speed has to be matched between the balancing)

**Comment by Karo4a** [comment]
What is the Uber LV machine? I don't understand what the upgrades configuration should be there

**Comment by Speiger** [comment]
Uber LV Machine => Loads of quantum/Overclockers + Efficiency upgrades in Upgrade containers.

**Comment by Karo4a** [comment]
Can you tell the specific values?

**Comment by Speiger** [comment]
Ask Greg he figured them out by himself.
I already forgot, everytime i plan to use them i ask him xD
No he has 0 sourcecode access he just was a tester

**Comment by Karo4a** [comment]
How i can find them?

**Comment by Speiger** [comment]
Not my problem.
