### ISSUE TITLE
Quantum chestplate with Module: Charger does not charge other items with a Nuclear Jetpack in the Back Slot

### ISSUE THREAD

**Issue by Karo4a** [TinyModularThings/IC2Classic#711]
When I put the nuclear jetpack in the back slot of my chestplate, it stops charging any items even with Module:Charger.

And can the control function be added to the Nuclear JetPack to change the start of charging and its end?
Because in battle, if your quantum chestplate does not charge at 70% of the total charge, then you will definitely lose.

**Comment by Speiger** [comment]
Nuclear Jeptack can not be charged since it has a nuclear reactor in it.
The idea is that you trade rechargability with a Nuclear Reactor.

All intenional.

**Comment by Karo4a** [comment]
I'm talking about the nuclear jetpack inside the quantum chestplate, not singly. When you start charging 20-25% in your chestplate, it's not cool. And if he creates energy inside the chestplate, why doesn't he share it with other items?

**Comment by Speiger** [comment]
@Karo4a because the nuclear jetpack disables all that functionality!

**Comment by Speiger** [comment]
```java
	@Override
	public void onInstall(ItemStack stack, ItemStack armor, IArmorModuleHolder holder)
	{
		super.onInstall(stack, armor, holder);
		holder.addMulModifier(armor, ArmorMod.ENERGY_TRANSFER, -1F);
		holder.addAddModifier(armor, ArmorMod.ENERGY_PROVIDER, -1000);
	}
```
The EnergyTransferMultiplier effectively negates any Transfer into the armor.
And The EnergyProvider value effectively negates any Transfer out of the armor.

About the 20-25% when the reactor starts to refill the armor.
That is because the nuclear reactor shouldn't run all the time. You don't want to waste fuel.
This also allows you to ensure the fuel is efficiently used!
