### ISSUE TITLE
Teleport tube does not graphically update the saved info at first enter

### ISSUE THREAD

**Issue by Karo4a** [TinyModularThings/IC2Classic#717]
First Enter: 
![image](https://user-images.githubusercontent.com/90093987/226571530-78bb5841-ea4c-4e24-a803-2b48f6a32a6e.png)
Second Enter:
![image](https://user-images.githubusercontent.com/90093987/226571597-eaff947d-98a6-4852-a245-269b50641376.png)

**Comment by Speiger** [comment]
This may or may not be a bug.
It may be a convenience feature. Ill have to look into that.
(TL:DR: The older versions had severe issues with typing lag because everytime the server edited something it would override what was written, because you were typing 2 character while it only send the first one back deleting that second one, dunno if that is nessesary anymore but you get the point)
