### ISSUE TITLE
Ic2 Drill not meeting tier requirements for Beyond Ores

### ISSUE THREAD

**Issue by EnderVonSlayer** [TinyModularThings/IC2Classic#720]

**Comment by Speiger** [comment]
@EnderVonSlayer turns out beyond Ores has hardcoded ores tier level detection.
It requires "TieredItem" to be a base class, which Pickeaxes/Shovels/Axes implement.
But if you have a custom implementation then that would break...
And we can not change that since that would require a rewrite.

I put a message on the CF page linking to this issue.
Lets hope he can fix that.
@GeekerAndy ping because that is something you need to know.

**Comment by Meduris** [comment]
just to add to this, this also affects mods like Mekansim.

simply using ``isCorrectToolForDrops`` for the check on beyond ores side, which is part of the Item baseclass, would fix this for both mods at the same time (and potentially many more otehrs too). Especially as ``isCorrectToolForDrops`` can be set on any tool, no matter how it is implemented or whether it extends TieredItem or not
