### ISSUE TITLE
curios battery issues

### ISSUE THREAD

**Issue by Developer2704** [TinyModularThings/IC2Classic#724]
when curios is installed the reusable battery, energy crystal and pesu are placable in curio slots but the glowtronic crystal and uesc is not.

**Comment by Speiger** [comment]
Yeah this is a unresolved issue during the design phase.
I am not sure how i am going to fix it since this went through multiple iterations until we got to this point.

Just to give a example if i would go by the first iterations potential solution before i thought why this is a problem:
I would have disabled the PESD for the curio slot.

Right now i have to evaluate all points and decide on disabling the PESD or enabling the 2 crystals.

Thanks for bringing this to my attention again xD
(As a small joke: If it goes away that makes you to blame for at this point then xDDD)
