### ISSUE TITLE
Reactor Track Upgrade

### ISSUE THREAD

**Issue by Teccco1993** [TinyModularThings/IC2Classic#745]
Hi, I have a problem with the Reactor Track Upgrade, I can use it to push LZH capacitors into the Reactor ( via machine buffer ) However it does not pull the capacitors out. I have used another buffer for the pull out. This was then on extract and mode condensers. Is it an operating error on my part or is this bugged? From what Dmg value should normally pull out the condensers?

**Comment by Teccco1993** [comment]
Hi, gives anyupdate to this Problem ^^?

**Comment by Speiger** [comment]
Sorry that i didn't answer.
The LZH Capacitors are pulled out by the reactor track upgrade if they have 10% or less durability left.
Aka the ideal spot regarding extraction.

Anyways if that is bugged you have to wait a bit since ic2c 1.12.2 is atm in a Cooldown cycle regarding the next patch.
A few weeks to say the least.
I do bulk updates with mods so most issues can be addressed and also to save time :)

**Comment by PootisManTF2** [comment]
Hello,

I was trying to make my nuclear reactor automatic and just came into this bug... I'm surprised it hasn't been patched yet since April :(

**Comment by Speiger** [comment]
@PootisManTF2 sorry but ic2c 1.12 updates are on a slow cycle.
There is usually like 5-6 months between updates at the very least.

Don't worry about "If" the bug gets fixed, but when.

**Comment by PootisManTF2** [comment]
@Speiger Why did you previously write "a few weeks to say the least" if it's actually whole months? 😔

**Comment by Speiger** [comment]
@PootisManTF2 its fixed with the next patch.

**Comment by Speiger** [comment]
@Teccco1993 its fixed with the next patch.
