### ISSUE TITLE
[Feature request] Compatibility with CC: Tweaked

### ISSUE THREAD

**Issue by Eggtosch** [TinyModularThings/IC2Classic#756]
I think IC2 Classic and CC: Tweaked might be a popular combination. I noticed that the Flux Generator's energy capacity and state can be read out because it implements the forge energy system, so would that at least be possible with the other machines?

**Comment by Speiger** [comment]
Ok what you are asking: Could you make every machine RF Compatible so people can also use RF to power these machines?

I know you want CC compat and that is fine to ask for :)
But I don't plan anytime soon to add that.

But you don't have to worry. There is someone who is adding support for it.
Its still in early dev but he is planning to expand a lot with it. And I am in contact with him and if he needs something I am adding support so he can make things work.

Here is the link to the plugin: [CFLink](https://www.curseforge.com/minecraft/mc-mods/cc-support-for-ic2)
Its only supporting the Monitors atm, which can already read a lot more information out then nothing. (Since the monitor can read out data from machines itself)
Yes it is a bit indirect atm but he plans to add direct ways too.

Anyways. Closing this issue since I don't plan to add it but gave you the info that someone is already working on an addon.
