### ISSUE TITLE
Suggestion. Allow Immersive engineering to power machines 1.19.2

### ISSUE THREAD

**Issue by detno** [TinyModularThings/IC2Classic#780]
Hello I been a fan of ic2 since tekkit. I'm a electrician as my real time job and I love how immersive engineering does with wires, power poles, relays, transformers, etc.
I know ie made industrial wires in the past. I seen ic2c has a flux generator and I believe a electric flux generator in the past. Can you revive the electric flux generator to convert rf to eu. I'll be mainly be using ic2c to power everything I just like the look and realism of power lines.

**Comment by Speiger** [comment]
No for a good reason.
RF is so fucking broken in its balance that you can NEVER balance for it. 
You are always screwing someone. Either you make it inaccessible in Early game because you account for all the late game crap or you are making endgame to overpowered because you only account for early game.
On top of that spam beats any balance i could even provide.

So there is no way from RF to EU directly and that most likely will never really change.

I am sorry :)

**Comment by Speiger** [comment]
@detno this is more addon territory tbh
