### ISSUE TITLE
crash server.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#807]
[crash-2023-06-10_10.08.41-server.txt](https://github.com/TinyModularThings/IC2Classic/files/11712588/crash-2023-06-10_10.08.41-server.txt)

**Comment by Speiger** [comment]
@MrJorman this bug is a really bad edge case that isn't easily produceable...
If you have a easy to reproduce setup with just ic2c that can be done in creative superflat world that would be great.
If you don't care if this bug is fixed just set: "Disable Crash Validation" to true.
Which doesn't fix the bug, but prevents crashes.

If you use the config just close the issue.
