### ISSUE TITLE
Incompatible with AtomicStryker's AdvancedMachines

### ISSUE THREAD

**Issue by axzxc1236** [TinyModularThings/IC2Classic#82]
Immibis' version works fine, but I prefer AtomicStryker's version because you can put upgrade in advanced machines, sadly it seems doesn't work with IC2Classic.

java.lang.NoClassDefFoundError: ic2/core/block/machine/tileentity/TileEntityStandardMachine

Full crash report : https://gist.github.com/axzxc1236/49e6a51281769c6b5610

**Comment by Speiger** [comment]
Knowen bug. Is Unfixable because he requires so much IC2 Exp classes that it would require rewrite the whole mod which it is not worth.
I will not do that.
What i did (finished yesterday) is implement Advanced Machines directly into classic.
Because Immibis version does not really work with classic.
This version has also has UpgradeSlots for machines (2 slots) but Overclocker will not work^^
Please wait for the next version it will come soon.

**Comment by axzxc1236** [comment]
okay, I will wait for updates.

**Comment by Speiger** [comment]
Sadly that will take a couple days... Maybe more because it is not just a little update that adds little stuff, nope this update is huge and not everything is done yet.
I hope that you can work without adv machines for now^^. If you really want them use immibis version (that has some trouble during worldload (cables connecting to his machines need to be replaced) but works fine^^)

**Comment by Carbon-Ghost** [comment]
And Speiger forgot to mention Induction furnaces also have upgrades now ;)

**Comment by Speiger** [comment]
Yeah...

**Comment by Speiger** [comment]
Closed
