### ISSUE TITLE
[BUG] Broken pipes and wires after teleportation.

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#830]
Please fix pipes and wires. When I teleport to my house or to the houses of the players, the pipes or wires are always buggy. I've posted screenshots before.

**Comment by Speiger** [comment]
@GitJhopa the reason why that happens is because you are losing TileEntityDataPackets.
The only way to fix that is to CONSTANTLY spam network packets, which will cause 2 things:
- Use up your datacap Really fast.
- Kill your FPS a LOT quicker.

I can't do anything about you losing Packets.
I already use the internal system from minecraft and not send dedicated packets to make this more reliable.
