### ISSUE TITLE
There is something wrong with a mod call: Create goggles

### ISSUE THREAD

**Issue by muheng111** [TinyModularThings/IC2Classic#833]
[crash-2023-07-08_15.13.21-fml.txt](https://github.com/TinyModularThings/IC2Classic/files/11992256/crash-2023-07-08_15.13.21-fml.txt)
IC2Classic Version: 2.0.6.2
Create Goggles Version: 0.5.5

**Comment by Speiger** [comment]
o/
The issue is with create goggles.
They collide with our ASM hook where we reimplement EU armor being able to absorb damage properly and not be a armor that can absorb only 80-90% of all damage. (that is a hardcoded cap)

Sadly the mod is 100% incompatible with Create Goggles.
Not sure why they need this "damage absorbtion hook" but it is what causes the issue.

**Comment by muheng111** [comment]
Thanks!
