### ISSUE TITLE
[SUGGESTION] What is missing in Ic2 classic.

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#841]
I saw in the topic that you are planning to make a major update for IC2 classic for new version of minecraft, and so I collected all the information from my 300+ players that they are missing:

**1.** Own ME network is normal (Applied Energistics - no, RefinedStorage - no)
**2.** Armor is higher than quantum, look at the logic of DragonicEvolution armor, something like that can be done so that crafting is very very very heavy, no simplicity for cool armor
**3.** I think it's worth removing the "Jetpack Slot" improvements from the table and adding an improved nano chestplate and a gravitational quantum chestplate, it will be more balanced and more difficult to craft
**4.** Add a sickle and lamps from RedProject, as there is a lack of tools for breaking grass or foliage, they were on the old versions 1.4.7 and 1.5.2 of minecraft and it was wonderful.

Do not judge strictly, but these are only suggestions that I received from a larger % of the players

**Comment by EnderVonSlayer** [comment]
Note 1: You do realize the industrial workbench with a fleshed out tube network and expansion slots essentially acts as manual ME system? If it's automated crafting you want, make factories or install AE or Refined storage. Maybe try and encourage your players to try using that system?
Note 2: How much power creep do you want? Nano and quantum already make you essentially immortal, just increase the storage crystal you want to use if you run out too quick
Note 3: The point of the modular armor system was to allow customizable armors. What part of that would be more balanced/more difficult to craft without being meaningless if it serves the same purpose? Also the gravitational armor addon is already leagues more costly.
Note 4: There already exists a mowing tool for removing large amount of grass/leaves

**Comment by GitJhopa** [comment]
> Note 1: You do realize the industrial workbench with a fleshed out tube network and expansion slots essentially acts as manual ME system? If it's automated crafting you want, make factories or install AE or Refined storage. Maybe try and encourage your players to try using that system? Note 2: How much power creep do you want? Nano and quantum already make you essentially immortal, just increase the storage crystal you want to use if you run out too quick Note 3: The point of the modular armor system was to allow customizable armors. What part of that would be more balanced/more difficult to craft without being meaningless if it serves the same purpose? Also the gravitational armor addon is already leagues more costly. Note 4: There already exists a mowing tool for removing large amount of grass/leaves

facts

**Comment by Speiger** [comment]
@GitJhopa so far all points i agree with @EnderVonSlayer. (Have to check if he has a mind read device implanted into my head)    

But lets review this:
- 1: I have no interest in "replacing ME/RS". There is a difference in providing tools and straight up making a modpack. The Industrial Worktable is there to aid you in "Crafting" since IC2 has a bad rep about to complex recipes. And a solution like the industrial Worktable is there to reduce this problem and provide tools so you can do things you wish, but not be so overpowered that you can not replace it.
- 2: Fun fact I dislike DragonicEvolution. In fact to the point where i say I will not play with it. In other words this will never happen. IC2C armor is fine the way it is. It is not unbeatable and yet it is really good.
- 3: The whole  reason the jetpack slot was added is the gravitational was so desired in the first place, because you don't want to give up armor for flying. I wonder why there is so many mods with Elytra Options in them. Ignoring all that, the idea being is that you can put jetpacks rather cheap into the armor but you are on a time budget since the armor can not be recharged from the outside. It is a balance act.
- 4: Mowing tool solves the grass/leaves problem. And is faster. About "ProjectRed Lamps". Dunno, but i am sure that I will not add ProjectRed Lamps. I might add Redpower lamps if that makes sense. But dunno yet. We will see :)
