### ISSUE TITLE
[Suggesion] RC Steam boiler

### ISSUE THREAD

**Issue by gfbbkon** [TinyModularThings/IC2Classic#874]
Good evening.
I would like to suggest adding steam boilers like in RailCraft: https://ftbwiki.org/Steam_Boiler_(Railcraft)
And also, if possible, add a multi-block tank where you can store liquids and steam.
In any case, thank you in advance.

**Comment by Speiger** [comment]
@gfbbkon have you actually played IC2Classic?

**Comment by Daenara** [comment]
I haven't tested if it can store steam but 1.19 has a multiblock tank which can be found in the ingame wiki

**Comment by gfbbkon** [comment]
> @gfbbkon have you actually played IC2Classic?

Yes, but the fuel boiler does not accept coal directly.

**Comment by gfbbkon** [comment]
> I haven't tested if it can store steam but 1.19 has a multiblock tank which can be found in the ingame wiki

Steam can be stored.

**Comment by Speiger** [comment]
@gfbbkon yeah that is by design.
But all you asked for is already part of the mod.
Modular Tanks that can look like railcraft tanks.
A Boiler Multiblock, that can produce steam etc.

So my question, have you played it?

But i am not going to straight up copying an entire mod.
I might add similar features but exact copies is kinda a "copyright" issue.
