### ISSUE TITLE
Armor & Rubber trees

### ISSUE THREAD

**Issue by draldan** [TinyModularThings/IC2Classic#89]
The Nano- and the Quantum Suits seem to not register damage properly. When I put either one of them on they won't help with damage reduction at all, no matter how charged they are.
   Also, it seems like rubber trees don't spawn in-game. Other than that it seems close to the old IC2 :)

**Comment by Speiger** [comment]
@draldan 
Please check next time the 1.1.0.x Milestone which represent the Update which is coming before you post something.
The RubberTree is already fixed. Was a Block Check mistake... (1.7.10 difference to 1.6.4)
and the aromor i will check&Test it but i am pretty sure that i already fixed that...

**Comment by Carbon-Ghost** [comment]
Now there is one thing we really need to fix... Make the rubber wood be able to rotate... I know it's wizardry/black magic but Speiger, we need to do it :D

**Comment by Speiger** [comment]
Do not know if there is enough Metadatas left.. Also resin spots would be not rotateable. (Would require 12 metadata only for resin spot)

**Comment by Carbon-Ghost** [comment]
I don't want "alive" wood to be able to be rotated, it won't need to anyway as it will always grow up straight ;P I want the chopped down wood ( normal ) to be able to be rotated :D

**Comment by ExDomino** [comment]
Where to check the milestone? And for the rubber tree, your mod is not playable until you fix that bug.
You could release a 1.0.9.11 with just that bug fixed.

**Comment by Speiger** [comment]
@ExDomino
i am fully aware of that fact. But these bugs are not the only onces that i need to fix. And this one you can fix with Minetweaker where you allow you to craft rubbertree saplings. (Until the fix is out)
You can find the Milestone under issus and on the top is a Button called Milestone or go to the Readme and click on the link i posted there...
And i can not code at the moment...
The only things i do is going to my meeting and when i am home i eat something and then sleeping time is already there.... I hope you understand my situation (for the next 6+ weeks),
i will use the weekend to make as much progress as i can. More is sadly not possible...

**Comment by Speiger** [comment]
Also I have no longer the source for 1.0.9.10 aviable (at least not in the current dev invioment), it is saved anywhere in my backup folders. And finding those would take way longer then making the acutial release happining.
Just for information we are currently at (dev state) 1.1.0.11 (12 is in progress) and i try to finish the 3 big projects as fast as possible. (Also Textures have to come before the release...)

**Comment by Speiger** [comment]
Is by the way totaly fixed...
