### ISSUE TITLE
Mining Laser Rebalance

### ISSUE THREAD

**Issue by CIoudmaker** [TinyModularThings/IC2Classic#896]
Good day.
From what i can see now, mining laser is quite inbalanced in terms of the effort to craft it. It's explosion mode is basically making obsolete other mining methods, because with minimal effort you can get huge amount of resources. I can't provide anything but my (and my friends') personal experience, but after aquiring it you don't have to got to the mines anymore, or to care about crafting autominers. Just shoot straight at desired height and in 5 or so minutes you are gonna have few stacks of ore, about 20-30 diamonds, some uranium etc.
What i suggest is adding an upgraded version, which requires like a plasma core to craft. Basic version still remains, but lacks two most powerful modes of it - explosion and tracking ones. These should be a feature of an advanced version.
I understand that the crafting recipe and features of the laser are coming from pretty old versions of IC2, but currently (and only from personal experience) the laser feels imbalanced. Most other content in this mod feels very consistent and straightforward in terms of crafting difficulty and posibilities it provides (maybe it feels so after playing IC2E 1.12 a lot lol) (probably except expansion upgrades for crop harvester), but the mining laser is just killing this feeling.

**Comment by Speiger** [comment]
Good day.

Ok i get your point. But hear me out.
Miners save you a lot of time by not linking you to the mining process at all.
And if you think the explosion mode is OP, then i know you haven't tried crops yet XD

The mining laser is outperformed by the crops.

Anyways. TL:DR the mining laser is a tool to aid you. If you think it is so strong that you have no reason to use anything else, then i am sorry to tell you the truth.
You are one of the very few people who think it is that way.
I rarely hear anyone actually using the mining laser in the first place :)

So power to you!

**Comment by CIoudmaker** [comment]
Well, it definitly isn't OP as opposed to another mining methods, but i didn't mean it is OP. As i feel it, it just doesn't fit in the curve well.
You have to spend some time to grow crops that will provide you that much resources (my gf spent like 1 or 2 evenings and the best she got is 7 3 0 iron crops). You have to craft an auto crop system to "unlink" yourself from the mining process. The expansion upgrade for harvester is pretty much a pain in the ass.
I didn't dig much in autominers, but i suppose they require some preps and lot of crafting too.
What's wrong with the mining laser in my opinion, is that it gives too much of a power at the moment you can craft it. Like, 5 composite plates, and two energy crystals is slightly above pure IC2C beginning, but the effect you get from it is literally groundbreaking at that point.
Ofc, after you get a crop farm done you will forget about the mining laser, but the sheer amount of power it provides THIS early just feels wrong.
Maybe plasma core to upgrade is really a killing nerf. I didn't spend much time in IC2C honestly, so i don't know about every OP way to get resources. I just shared my feellings about how well every other machine/generator/tool/etc fits in the global curve and how the mining laser (in my opinion) does not.

**Comment by Speiger** [comment]
> You have to spend some time to grow crops that will provide you that much resources (my gf spent like 1 or 2 evenings and the best she got is 7 3 0 iron crops).

Yeah, that is actually impressive. It is hard to maintain a 0, if she didn't focus on that then she would be already on a ~20 ~20 ~20. Though i have seen crazy people that have done a 31, 31, 0 because they are insane like that.
Note that the gain stat is effectively a exponential stat, not a liniar.

> You have to craft an auto crop system to "unlink" yourself from the mining process. The expansion upgrade for harvester is pretty much a pain in the ass.

Wait they are? Aren't they just easy crafting components + dense copper plates + macerating a few coal blocks?
I know its a few recipes but massproducing them in a industrial worktable is like easy.

> I didn't dig much in autominers, but i suppose they require some preps and lot of crafting too.

Eh, not that much. Once you have the components you can recycle them and the only thing you really need a lot of is mining pipes...

> What's wrong with the mining laser in my opinion, is that it gives too much of a power at the moment you can craft it. Like, 5 composite plates, and two energy crystals is slightly above pure IC2C beginning, but the effect you get from it is literally groundbreaking at that point.

Yeah and that shows you don't run into its cost so easily because you seem to have at least your planning phase relatively well thought out.
A mining laser gets 40 shots out of its power storage, in explosion mode. Which sounds like a lot but for mining like you suggest it you need a few hundred shots so you are at least draining a MFE rather quickly.

And by the point you are capable of crafting it, a lot of player usually don't have a good power system with it.
The actual costs are the power requirements that are on it.
A real re-balancing wouldn't be on the "entrance cost" like you suggest but on the maintenance cost, which you seem to forget.
5kEU per shot is expensive AF... 
That is 25% of a lava bucket or more then one piece of coal.

> Ofc, after you get a crop farm done you will forget about the mining laser, but the sheer amount of power it provides THIS early just feels wrong.

Oh boy. You don't realize that people can get a crop field done before they have done their first mining trip.
its all wood based what you need.
And yes you do need some ores, but when you get the metal crops, which is the harder of the two to reach you can go down grab a couple ores and make a block form with your first furnace, and bam you have production.
(Yes you do need ores to get a crop scanner, but its less then you think :), and no you don't need metals to run the item, single use batteries/redstone dust!)

> Maybe plasma core to upgrade is really a killing nerf. I didn't spend much time in IC2C honestly, so i don't know about every OP way to get resources. I just shared my feelings about how well every other machine/generator/tool/etc i used fits in the global curve and how the mining laser (in my opinion) does not.

Plasma core tier is stuff that REALLY needs it, like extremely op things, or things that i personally don't agree with but was kinda forced to add too, or for the players i want to send the middlefinger to, (I look at you the useless wrench upgrade).

Anyways, i get your point, but i hole hardly disagree.
While i see some balance requirements for it in general, it is not the kind of balance you think or request.
Also IC2Classic is already so grindy that drips of joy like the mining laser should be present :)

It might change in the "3.0.0" version (1.7.10 was 1.0, 1.10.2-1.12 was 1.5, and 1.19.2 was 2.0) but the current versions stay that way.

Overall thank you for the feedback :)

Glad that you enjoy the mod!
