### ISSUE TITLE
[1.19.2] incompatibility Ic2  with CC:tweaked?

### ISSUE THREAD

**Issue by CactusGame4** [TinyModularThings/IC2Classic#899]
Hi everyone, 
I've found a bug ?? or incompatibility  with CC:Tweaked , with computer all of the storage block (or nuclear reactor ect...) is configurate like storage , so we have not methods to have Energy stored or a Capacity.
I'm already discuss with the discord's cc:tweaked and they say it must have an implementation.
So can you , or with me ,make all the storage blocks implemented :).

**Comment by Speiger** [comment]
@CactusGame4 we do not have a Compat with CC:Tweaked.
And since we have our own EnergyAPI they simply either have to support our API or we do have to implement theirs.

IC2Classic itself has atm no plans to actively support CC:Tweaked.
Though we would support with information if someone wants to make either the implementation in CC:Tweaked or make an addon.
