### ISSUE TITLE
Barrel related Tooltip improvments

### ISSUE THREAD

**Issue by gudvinr** [TinyModularThings/IC2Classic#915]
Edited by Speiger because the issue has been solved and suggestions came out:

- [x] Mention the thermometer in the brewing section, and what it does
- [x] Provide Tooltips on the barrel that show what is inside, in a meaningful way.

**Comment by Speiger** [comment]
Water is the finishing step.
So you start technically beer brewing and then you try to turn it into whisky.


I mean when you make coffee or Kakao you don't put in the water/milk first and then put in the powder, right?

**Comment by gudvinr** [comment]
> I mean when you make coffee or Kakao you don't put in the water/milk first and then put in the powder, right?

I do make kakao like that though... Warm milk first and then add powder

**Comment by Speiger** [comment]
I am no one to judge xD

**Comment by CrossVas** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/a911400b-5c4d-4194-bd02-7e99444bb22e)
You need this in your hotbar or Helmet (for advanced armor). 

https://github.com/TinyModularThings/IC2Classic/assets/25727222/18b26b9c-fe01-4625-a1b3-2bf2d1c6b393

**Comment by gudvinr** [comment]
Yup, doing that, HUD appears but instead of getting whisky I am getting this:

[brewing.webm](https://github.com/TinyModularThings/IC2Classic/assets/1712806/3433b919-d2ff-4d7e-984e-ae0ab843f0bd)

**Comment by gudvinr** [comment]
Jesus, I get it now.

It turns out that Barrel is not the same as Barrel.  
I was placing Barrel but what I was needed to put is Barrel.

Why is filled Barrel has no indication that it is not the same as empty Barrel like e.g cell?

Not only that but there is no mention of thermometer in brew manual either.  
Thermometer itself only mentioned as a tool for reactor.

**Comment by Speiger** [comment]
> Not only that but there is no mention of thermometer in brew manual either.
Thermometer itself only mentioned as a tool for reactor.

Fair point.
That is a change worthy idea.

> Why is filled Barrel has no indication that it is not the same as empty Barrel like e.g cell?

Also a good idea ^^"

Just a note, the wiki is huge and the mod is huge, stuff gets missed because there is very few people working on it.
That means there is a lot of potential for missing stuff.
And we had 2 betas running over months to ensure that a lot of things get found (and I rewrote a LOT of the sections that existed before the release because it was way worse back then).
But we are not perfect.

Anyways, Reopening this and changing the name to make it a proper issue that can be addressed next patch, whenever that one comes :)

**Comment by gudvinr** [comment]
> the wiki is huge and the mod is huge

True

> But we are not perfect.

No probs, sky is the limit. It's always better to move forward and improve yet being imperfect rather than do nothing at all.
