### ISSUE TITLE
Incompatible with railcraft

### ISSUE THREAD

**Issue by axzxc1236** [TinyModularThings/IC2Classic#92]
I've already tried disable ic2 module in railcraft config file, but it doesn't work.
[crash log](http://openeye.openmods.info/crashes/047cfaca7e93c21f17ca60e5bc897a66)

**Comment by dustojnikhummer** [comment]
Strange,i have pack with IC2C and Railcraft and it works fine. Do you have BluePower in pack?

**Comment by axzxc1236** [comment]
No

**Comment by Speiger** [comment]
@axzxc1236
that has nothing todo with other mods...
Its a IC2 Config bug. You caused it, but it can be fixed really easy.
Just remove the Recycler Blacklist part completly so that part Recreates.
Has something todo that it still uses ids and has a preSet Ids has and because you added mods after that that the block he trys to load no longer exsist...
Update changes that and solves that problem forever...

**Comment by Carbon-Ghost** [comment]
Yeah, we don't recommend touching the IC2 exp configs in RC :P 

Otherwise it works just fine ^^

**Comment by axzxc1236** [comment]
Thanks, my problem solved.

**Comment by Speiger** [comment]
Np.
