### ISSUE TITLE
Changing multiblock textures

### ISSUE THREAD

**Issue by Fxkz** [TinyModularThings/IC2Classic#940]
The idea of making a multiblock by simply magnifying a texture several times is the worst thing you could think of. If the steam turbine still has a logical explanation for its size, the crusher, against which you look like an ant - it's just awful and does not fit the game in any way. You can easily fix this by creating a multiblock using the same logic as the blast furnace and coke oven - it will look much better than what you have now. I hope you take heed and fix this with all 2x2 and larger multiblocks (except steam turbines). It's not a hard thing to do

**Comment by Speiger** [comment]
That would make (96 + 54 + 24) * 6 textures so 1044 unique textures.

First Personally I think a scaled up macerator looks way cooler.
We technically had plans to make more interesting stuff.
But both time + money were kinda an issue.

Because I expect to pay an artist to do such work, not do it for free, since we don't have dedicated artists in the team.
and even then i consider paying them.

So lets say we make 256 unique 16x16 textures thats still a quarter grand to pay.
Because I don't plan to make these BlockEntity Models, they are the way they are because its much more efficient on your CPU overall.

The solution was basically a time/cost/performance effective solution and one i actually liked for the way it looked ingame,
and i don't plan to change that.
