### ISSUE TITLE
[1.19.2] Industrial Craft 2 Classic Wiki book changes GUI Scale when opened

### ISSUE THREAD

**Issue by rotkudnoK** [TinyModularThings/IC2Classic#948]
Pretty much the title. 

Here's my normal GUI Scale (set to 2):
![image](https://github.com/TinyModularThings/IC2Classic/assets/17196454/c17ab54c-eee4-4156-aabf-0d9c1338da6f)

And here's the Scale with the book open (looks like GUI Scale 4)
![image](https://github.com/TinyModularThings/IC2Classic/assets/17196454/e0ddd104-d1b5-4274-a83d-67d9890a985d)

**Comment by Geekerandy** [comment]
This is an intentional feature so you can read the book more easily.

**Comment by Speiger** [comment]
If you use a 2K monitor or anything larger then 1k (1080p) you will not be able to read it.
So what we are doing is always ensuring you are running a 720p Gui because that has been the best resolution we found.
(Minecraft guis are designed to run in 480p actually)

**Comment by rotkudnoK** [comment]
> If you use a 2K monitor or anything larger then 1k (1080p) you will not be able to read it

I don't think that's true. If one struggles to read on 2k monitor, one simply has to adjust his in-game GUI Scale. That's literally the purpose of this option, is it not?

And vice-versa, if I find the GUI and text too large I should have the option to make it smaller

**Comment by Speiger** [comment]
@rotkudnoK I had multiple testers complain that they constantly had to do that because otherwise the wiki was unreadable.
And they had different UI ranges as default.
From 720p to 4k.

And 99% of the complainers agreed that the current solution works well.
Because 1: They don't have to manually scale everything every single time and it doesn't break their preferred setup.
And the wiki stays readable.

Anyways.
It stays that way
