### ISSUE TITLE
Crash with Botarium mod

### ISSUE THREAD

**Issue by Sford1Keep** [TinyModularThings/IC2Classic#950]

**Comment by Sford1Keep** [comment]
Crash with Botarium modNew versions of Botarium mod are incompatible with IC2 Classic. Gives a rendering error. Can't scroll beyond 12, always crashes. Versions above 1.8.2 lead to crash. Crashes on Forge.

**Comment by Meduris** [comment]
Can you please post the crash log here?

**Comment by Sford1Keep** [comment]
Here's the crash report, hopefully needed. Since it took me a relatively long time to figure out what the problem was.
[crash-2024-01-23_17.52.30-client.txt](https://github.com/TinyModularThings/IC2Classic/files/14027083/crash-2024-01-23_17.52.30-client.txt)

**Comment by Sford1Keep** [comment]
Even though the crash report says it's because of the guidebook, it's not just because of the guidebook. In previous crashes there were other reasons. For example bronze shield, personal chest (which is safe), advanced comparator. Here I found the crash report with bronze shield.
[crash-2024-01-22_21.11.50-client.txt](https://github.com/TinyModularThings/IC2Classic/files/14027127/crash-2024-01-22_21.11.50-client.txt)

**Comment by Sford1Keep** [comment]
Figuring out how I even blacklisted one of the items, namely the personal safe for JEI, but afterward it would expose another item for the culprit.

**Comment by altriix** [comment]
having the same issue here, affected items:
Personal Chest, all shields from IC2C, advanced comparator - had to block them in game and in JEI using a mod so was able to scroll through, thought this was the only problem but then the below as well :(
When placing a barrel into scaffolding game crashes, same when placing Macerator, Extractor etc.
All logs below
[crash-2024-01-30_20.41.00-client.txt](https://github.com/TinyModularThings/IC2Classic/files/14103987/crash-2024-01-30_20.41.00-client.txt)
[crash-2024-01-30_20.43.15-client.txt](https://github.com/TinyModularThings/IC2Classic/files/14103988/crash-2024-01-30_20.43.15-client.txt)
[crash-2024-01-30_20.44.13-client.txt](https://github.com/TinyModularThings/IC2Classic/files/14103989/crash-2024-01-30_20.44.13-client.txt)

**Comment by Speiger** [comment]
Will be fixed with the next patch which should come out within February.

**Comment by Guargest** [comment]
Had the same issue, because i downloaded an old version from curseforge. Sorry if i'm being dumb but i couldn't figure out how to compile a jar mod file, i ran gradle bat file and it gave me forge jar instead of ic2 jar, i even renamed the forge jar it gave me but the minecraft crashed at start. If your patch is ready, could you please guide me how to get ic2 jar file, i am completely lost
[crash-2024-02-25_14.40.41-client.txt](https://github.com/TinyModularThings/IC2Classic/files/14396049/crash-2024-02-25_14.40.41-client.txt)
![image](https://github.com/TinyModularThings/IC2Classic/assets/161203584/392f9061-bd32-4681-9e79-6897a82c776b)
