### ISSUE TITLE
CFoam backpack supply foam only from armor slot

### ISSUE THREAD

**Issue by DmitryProskurin** [TinyModularThings/IC2Classic#956]
You can place it to back slot, but it can't provide CFoam to electric CFoam sprayer. It works only from chest plate armor slot.

Minecraft 1.19.2
Mods:
Forge 43.3.0
IC2 Classic 2.0.8.1
Curious API 5.1.5.0
The One Probe 6.2.2

**Comment by DmitryProskurin** [comment]
Not related, but in recipe of HV Solar palnel used IV transformer! May be should use HV transformer instead?

**Comment by Speiger** [comment]
@DmitryProskurin thank you. Yes that is technically a bug.

About the solar panel:
No that is not a bug, that is intentional, since ever since compact solars was integrated into ic2classic people only focused on that.
And it is one of the worst ways to produce power at scale.
And since people ignored everything else and started complaining about how bad their power production was i basically added a shock recipe into the HV solar panels that they wouldn't even consider it.
And that has been very effective so far.

Because a lot of people look at the first recipe: See its stupid expensive and don't even check the recipes before it since they don't value the LV/MV ones at all.

**Comment by DmitryProskurin** [comment]
@Speiger It's become even more expensive, when you want craft ultimate hybrid solar panel from Advanced Solars Classic 😂.

**Comment by Speiger** [comment]
@DmitryProskurin yeah because i showed the dev how badly they were balanced :)
