### ISSUE TITLE
[1.19.2] Wrong recipe for HV Solar Panel

### ISSUE THREAD

**Issue by RodionRybakov** [TinyModularThings/IC2Classic#962]
Recipe for _HV Solar Panel_ (512 EU/t output) requires _IV Transformer_ (tier 5) instead of _HV Transformer_ (tier 3).
<img width="433" alt="recipe1" src="https://github.com/TinyModularThings/IC2Classic/assets/7754354/c82cba69-0139-4759-9e78-1861fa756d9a">

_IV Transformer_ itself has a quite expensive craft to be used just as an intermediate component:
<img width="382" alt="recipe2" src="https://github.com/TinyModularThings/IC2Classic/assets/7754354/c4b3e418-b01a-43ef-931d-22bdb818d672">

**Comment by Speiger** [comment]
@RodionRybakov not wrong. It is correct

**Comment by RodionRybakov** [comment]
Any particular reason for that? All the places I searched use much lower tier transformer. For example: https://feed-the-beast.fandom.com/wiki/High_Voltage_Solar_Array
I suppose recipe changed only in this IC2 classic version. Any detailed info appreciated.

**Comment by Speiger** [comment]
@RodionRybakov it is basically a slap into people faces.
Mainly because most players instantly try to build only HV solar panels and nothing else and ignore all the other actually good solutions out there.

And that usually wakes people up and they either drop the mod or actually start using the mod properly.
Usually they don't look at MV solar panels in the first place.

**Comment by RodionRybakov** [comment]
OK, thanks
