### ISSUE TITLE
Pipe filters not working with copy tool

### ISSUE THREAD

**Issue by AngryDatchund** [TinyModularThings/IC2Classic#971]
If you copy filters from pipe1 to pipe2 - pipe2 not working at all. You can fix that by adding new filter in pipe2 or toggle blacklist/whitelist twice

**Comment by Speiger** [comment]
@AngryDatchund could you specify the tube or fluid pipe you used?

**Comment by AngryDatchund** [comment]
@Speiger default tube. It also works with any pipes

**Comment by Speiger** [comment]
@AngryDatchund yeah please show me a video of which you specifically mean since you said "Default tube"
Which doesn't have any settings.
Here is the proof that i picked a random filter tube and it worked just fine.
https://youtu.be/y0xtQR3-O-I

If you make such a broad case I can only test so many things before i run out of time.

**Comment by AngryDatchund** [comment]
@Speiger you need to relog after you copy filter

1) Copy filter
2) Paste
3) Relog
4) Check pipes working

**Comment by Speiger** [comment]
https://github.com/TinyModularThings/IC2Classic/assets/2556269/e40b0759-3e55-47e5-bbc4-f19cb4e04e60

You mean like this?
If the next comment doesn't provide video proof then I will assume this being a troll report.
Because I now did it the exact way you wanted it.
